const CURRICULUM = {
  title: "AI Backend Engineer Mastery",
  subtitle: "Docker → Kubernetes → Cloud → AI/ML Production Systems",
  totalWeeks: 20,
  phases: [
    {
      id: "phase-1",
      title: "Phase 1: Containerization & Backend Foundations",
      color: "#3b82f6",
      weeks: "1–4",
      modules: [
        {
          id: "m1",
          title: "Docker Deep Dive",
          week: "Week 1–2",
          icon: "🐳",
          duration: "2 weeks",
          description: "Master containerization — the foundation of everything else in this curriculum.",
          topics: [
            "What is Docker? VMs vs containers",
            "Images, layers, Dockerfile authoring",
            "docker build, run, exec, logs, inspect",
            "Volumes, bind mounts, networking (bridge, host, overlay)",
            "Docker Compose — multi-container apps",
            "Multi-stage builds for lean production images",
            "Docker registries (Docker Hub, ECR, GCR, Artifact Registry)",
            "Security: non-root users, read-only filesystems, image scanning (Trivy)",
          ],
          labs: [
            {
              title: "Containerize a FastAPI App",
              desc: "Write a Dockerfile for a Python FastAPI app. Use multi-stage build to keep the image small. Push to Docker Hub.",
              difficulty: "beginner",
            },
            {
              title: "Multi-Service Compose Stack",
              desc: "Spin up FastAPI + PostgreSQL + Redis using Docker Compose with named volumes, health checks, and a custom network.",
              difficulty: "intermediate",
            },
            {
              title: "Image Security Audit",
              desc: "Scan your images with Trivy. Reduce CVEs by switching base images and using non-root users.",
              difficulty: "intermediate",
            },
          ],
          resources: [
            { title: "Docker Official Docs", url: "https://docs.docker.com/get-started/" },
            { title: "Play with Docker (free sandbox)", url: "https://labs.play-with-docker.com/" },
            { title: "Dockerfile Best Practices", url: "https://docs.docker.com/develop/develop-images/dockerfile_best-practices/" },
            { title: "Trivy — Image Scanner", url: "https://github.com/aquasecurity/trivy" },
          ],
          interviewQuestions: [
            "What is the difference between CMD and ENTRYPOINT?",
            "How do Docker layers work, and why does layer caching matter for CI?",
            "Explain the difference between COPY and ADD.",
            "How would you reduce Docker image size for a Python app?",
            "What's the difference between bridge, host, and overlay networks?",
            "How do you share secrets securely in Docker? (not ENV variables)",
          ],
          systemDesign: null,
        },
        {
          id: "m2",
          title: "Python + FastAPI for Production",
          week: "Week 2–3",
          icon: "⚡",
          duration: "2 weeks",
          description: "Build production-grade async APIs with FastAPI — the dominant Python backend framework in AI engineering.",
          topics: [
            "Async Python: event loop, async/await, asyncio",
            "FastAPI fundamentals: routes, Pydantic models, dependency injection",
            "Middleware: CORS, rate limiting, request logging",
            "Background tasks and lifespan events",
            "JWT authentication with OAuth2",
            "OpenAPI docs, versioning, structured error handling",
            "Testing: pytest, httpx AsyncClient, mocking",
            "Production: Uvicorn + Gunicorn workers, health check endpoints",
          ],
          labs: [
            {
              title: "Build a URL Shortener API",
              desc: "FastAPI + PostgreSQL + Redis for caching. Include auth, pagination, and a /health endpoint. Containerize it.",
              difficulty: "beginner",
            },
            {
              title: "Rate-Limited AI Inference API",
              desc: "Wrap a HuggingFace model behind a FastAPI endpoint. Add Redis-based rate limiting per API key.",
              difficulty: "intermediate",
            },
            {
              title: "Background Job Queue",
              desc: "Use FastAPI BackgroundTasks + Celery + Redis to process long-running tasks asynchronously.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "FastAPI Official Docs", url: "https://fastapi.tiangolo.com/" },
            { title: "Pydantic v2 Docs", url: "https://docs.pydantic.dev/latest/" },
            { title: "Async Python for Beginners", url: "https://realpython.com/async-io-python/" },
            { title: "FastAPI Best Practices (GitHub)", url: "https://github.com/zhanymkanov/fastapi-best-practices" },
          ],
          interviewQuestions: [
            "How does FastAPI's dependency injection work?",
            "What's the difference between async def and def in FastAPI?",
            "How would you implement API versioning?",
            "How do you handle long-running tasks without blocking the event loop?",
            "Explain Pydantic's role in request validation.",
            "How do you write integration tests for a FastAPI app that uses a real DB?",
          ],
          systemDesign: null,
        },
        {
          id: "m3",
          title: "Databases: PostgreSQL, MongoDB, Redis",
          week: "Week 3–4",
          icon: "🗄️",
          duration: "2 weeks",
          description: "Master the three database types you'll use in every production system.",
          topics: [
            "PostgreSQL: transactions, ACID, indexes (B-tree, GIN, partial), EXPLAIN ANALYZE",
            "SQLAlchemy async ORM + Alembic migrations",
            "Connection pooling (PgBouncer, asyncpg pools)",
            "MongoDB: document model, aggregation pipeline, Atlas Search",
            "Redis: data structures (string, list, set, sorted set, hash, stream)",
            "Redis patterns: caching, session store, pub/sub, distributed locks, rate limiting",
            "Database design: normalization vs denormalization, sharding strategies",
            "Read replicas and write-ahead logs",
          ],
          labs: [
            {
              title: "PostgreSQL Query Optimization",
              desc: "Load 1M rows of e-commerce data. Write slow queries, use EXPLAIN ANALYZE, add the right indexes, measure improvement.",
              difficulty: "intermediate",
            },
            {
              title: "Redis Caching Layer",
              desc: "Add Redis caching to your FastAPI app with cache invalidation logic. Implement a distributed lock for a shared resource.",
              difficulty: "intermediate",
            },
            {
              title: "MongoDB Aggregation Pipeline",
              desc: "Design a log analytics pipeline using MongoDB aggregation. Group, filter, and compute metrics from raw event documents.",
              difficulty: "intermediate",
            },
          ],
          resources: [
            { title: "PostgreSQL Tutorial", url: "https://www.postgresqltutorial.com/" },
            { title: "Use The Index, Luke!", url: "https://use-the-index-luke.com/" },
            { title: "Redis University (Free)", url: "https://university.redis.com/" },
            { title: "MongoDB University (Free)", url: "https://university.mongodb.com/" },
          ],
          interviewQuestions: [
            "When would you choose MongoDB over PostgreSQL?",
            "What is a database index? Explain B-tree vs GIN.",
            "How does Redis handle persistence (RDB vs AOF)?",
            "What is connection pooling and why does it matter?",
            "Explain the CAP theorem with examples.",
            "How do you implement optimistic vs pessimistic locking?",
          ],
          systemDesign: null,
        },
      ],
    },
    {
      id: "phase-2",
      title: "Phase 2: Kubernetes & Cloud Infrastructure",
      color: "#8b5cf6",
      weeks: "5–8",
      modules: [
        {
          id: "m4",
          title: "Kubernetes Fundamentals",
          week: "Week 5–6",
          icon: "☸️",
          duration: "2 weeks",
          description: "Kubernetes is the operating system of the cloud. Learn to run, scale, and manage containerized workloads.",
          topics: [
            "Architecture: control plane (API server, etcd, scheduler, controller manager) vs worker nodes (kubelet, kube-proxy, container runtime)",
            "Core objects: Pod, Deployment, ReplicaSet, Service (ClusterIP, NodePort, LoadBalancer), Namespace",
            "kubectl: apply, get, describe, logs, exec, port-forward, top",
            "ConfigMaps and Secrets (sealed secrets, External Secrets Operator)",
            "Persistent Volumes (PV), PVCs, StorageClasses",
            "Resource requests and limits, QoS classes",
            "Health checks: liveness, readiness, startup probes",
            "Rolling updates, rollbacks, deployment strategies (RollingUpdate, Recreate, blue-green, canary)",
          ],
          labs: [
            {
              title: "Deploy FastAPI to Kubernetes",
              desc: "Write Deployment + Service + ConfigMap YAMLs. Deploy your Dockerized FastAPI app to a local cluster (minikube or kind). Expose it with a Service.",
              difficulty: "beginner",
            },
            {
              title: "Horizontal Pod Autoscaling",
              desc: "Configure HPA based on CPU/memory. Load test with k6 and watch pods scale up and down.",
              difficulty: "intermediate",
            },
            {
              title: "Zero-Downtime Rolling Deploy",
              desc: "Configure maxUnavailable/maxSurge. Simulate a rolling update and verify zero downtime with a continuous curl loop.",
              difficulty: "intermediate",
            },
          ],
          resources: [
            { title: "Kubernetes Official Docs", url: "https://kubernetes.io/docs/home/" },
            { title: "Killercoda K8s Playground (Free)", url: "https://killercoda.com/playgrounds/scenario/kubernetes" },
            { title: "K8s the Hard Way (Kelsey Hightower)", url: "https://github.com/kelseyhightower/kubernetes-the-hard-way" },
            { title: "kubectl Cheat Sheet", url: "https://kubernetes.io/docs/reference/kubectl/cheatsheet/" },
          ],
          interviewQuestions: [
            "What happens when you run `kubectl apply -f deployment.yaml`?",
            "Explain the difference between a Pod and a Deployment.",
            "How does a Service route traffic to Pods?",
            "What is the difference between liveness and readiness probes?",
            "How would you debug a CrashLoopBackOff?",
            "Explain resource requests vs limits. What is a QoS class?",
          ],
          systemDesign: {
            prompt: "Design a Kubernetes deployment for a high-traffic FastAPI service that processes AI inference requests. The service must autoscale, have zero-downtime deploys, and expose metrics.",
            hints: [
              "HPA + custom metrics (KEDA for queue-based scaling)",
              "PodDisruptionBudget for availability during upgrades",
              "Readiness probe to hold traffic until model is loaded",
              "Prometheus ServiceMonitor for scraping",
            ],
          },
        },
        {
          id: "m5",
          title: "Kubernetes Advanced: Networking, Storage, Security",
          week: "Week 6–7",
          icon: "🔧",
          duration: "1.5 weeks",
          description: "Go beyond basics — learn production patterns for networking, storage, RBAC, and multi-tenancy.",
          topics: [
            "Ingress controllers (NGINX, Traefik) and IngressClass",
            "Network policies — default deny, allow specific flows",
            "Service mesh basics (Istio/Linkerd): mTLS, traffic splitting, observability",
            "StatefulSets: stable network identity, ordered scaling (for databases, Kafka)",
            "DaemonSets (log agents, node exporters)",
            "RBAC: Role, ClusterRole, RoleBinding, ServiceAccounts",
            "Pod Security Standards / OPA Gatekeeper",
            "Multi-tenancy: namespaces, resource quotas, LimitRanges",
          ],
          labs: [
            {
              title: "Ingress with TLS",
              desc: "Set up NGINX Ingress Controller. Configure cert-manager with Let's Encrypt for automatic TLS. Route traffic to two different services by path.",
              difficulty: "intermediate",
            },
            {
              title: "Network Policy: Zero Trust",
              desc: "Implement a default-deny NetworkPolicy. Explicitly allow: frontend→API, API→DB, monitoring→all. Verify with kubectl exec tests.",
              difficulty: "advanced",
            },
            {
              title: "StatefulSet for PostgreSQL",
              desc: "Deploy PostgreSQL as a StatefulSet with a PVC per replica. Test pod deletion and observe stable identity recovery.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "Network Policies Explained", url: "https://kubernetes.io/docs/concepts/services-networking/network-policies/" },
            { title: "Ingress Controllers Comparison", url: "https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/" },
            { title: "RBAC Deep Dive", url: "https://kubernetes.io/docs/reference/access-authn-authz/rbac/" },
          ],
          interviewQuestions: [
            "How does Kubernetes networking work? What is CNI?",
            "When would you use a StatefulSet vs a Deployment?",
            "Explain RBAC. How do you give a pod access to Kubernetes API?",
            "What is a network policy, and how does it differ from a firewall rule?",
            "How does cert-manager automate TLS certificate management?",
          ],
          systemDesign: null,
        },
        {
          id: "m6",
          title: "CI/CD Pipelines",
          week: "Week 7",
          icon: "🔄",
          duration: "1 week",
          description: "Automate the full path from code to production.",
          topics: [
            "CI/CD concepts: continuous integration vs delivery vs deployment",
            "GitHub Actions: workflows, jobs, steps, secrets, matrix builds",
            "Docker image build + push in CI",
            "GitOps with ArgoCD: sync from git to cluster",
            "Helm: charts, values, templating, releases",
            "Kustomize: overlays for dev/staging/prod",
            "Canary deployments with Argo Rollouts",
            "Security: SAST, container image scanning in pipeline",
          ],
          labs: [
            {
              title: "GitHub Actions Pipeline",
              desc: "Build a pipeline: test → lint → docker build → push to registry → update K8s deployment. Trigger on PR and main branch push.",
              difficulty: "intermediate",
            },
            {
              title: "ArgoCD GitOps Setup",
              desc: "Install ArgoCD. Create an Application manifest pointing to your Helm chart in git. Push a change and watch ArgoCD sync it.",
              difficulty: "intermediate",
            },
            {
              title: "Helm Chart from Scratch",
              desc: "Package your FastAPI app as a Helm chart with configurable replicas, image tag, resource limits, and ingress toggle.",
              difficulty: "intermediate",
            },
          ],
          resources: [
            { title: "GitHub Actions Docs", url: "https://docs.github.com/en/actions" },
            { title: "ArgoCD Getting Started", url: "https://argo-cd.readthedocs.io/en/stable/getting_started/" },
            { title: "Helm Docs", url: "https://helm.sh/docs/" },
          ],
          interviewQuestions: [
            "What is the difference between CI and CD?",
            "What is GitOps and how does ArgoCD implement it?",
            "How do you safely roll back a bad deployment?",
            "What is Helm? When would you use Kustomize instead?",
            "How do you handle secrets in CI/CD pipelines?",
          ],
          systemDesign: null,
        },
        {
          id: "m7",
          title: "Cloud Platforms: GCP / AWS / Azure",
          week: "Week 8",
          icon: "☁️",
          duration: "1 week",
          description: "Learn the core cloud primitives you'll use in every production system.",
          topics: [
            "Compute: Cloud Run, Lambda, EC2, GCE, App Engine",
            "Storage: S3/GCS/Azure Blob, EBS/persistent disks",
            "Managed K8s: GKE, EKS, AKS — differences, autopilot vs standard",
            "IAM: roles, service accounts, workload identity",
            "Networking: VPC, subnets, NAT, load balancers, Cloud CDN",
            "Serverless: Cloud Run (GCP), Lambda (AWS), Container Apps (Azure)",
            "Cloud Functions vs Cloud Run — when to use each",
            "Cost management: spot/preemptible instances, committed use discounts",
          ],
          labs: [
            {
              title: "Deploy to Cloud Run",
              desc: "Push your FastAPI image to Google Artifact Registry. Deploy to Cloud Run with auto-scaling min=0. Add a custom domain.",
              difficulty: "beginner",
            },
            {
              title: "GKE Autopilot Cluster",
              desc: "Create a GKE Autopilot cluster. Deploy your app via Helm. Set up Workload Identity to access GCS from a pod.",
              difficulty: "intermediate",
            },
            {
              title: "IAM Least Privilege",
              desc: "Audit an over-permissioned service account. Create a custom IAM role with only the permissions needed. Verify access.",
              difficulty: "intermediate",
            },
          ],
          resources: [
            { title: "GCP Free Tier", url: "https://cloud.google.com/free" },
            { title: "AWS Free Tier", url: "https://aws.amazon.com/free/" },
            { title: "Cloud Run Quickstart", url: "https://cloud.google.com/run/docs/quickstarts" },
            { title: "GCP Architecture Center", url: "https://cloud.google.com/architecture" },
          ],
          interviewQuestions: [
            "When would you use Cloud Run vs GKE vs Cloud Functions?",
            "Explain IAM roles vs service accounts.",
            "What is Workload Identity and why is it better than service account keys?",
            "How does an Application Load Balancer differ from a Network Load Balancer?",
            "What are spot/preemptible instances and when would you use them for AI workloads?",
          ],
          systemDesign: {
            prompt: "Design a serverless AI inference system that costs near-zero when idle but handles burst traffic of 1000 req/s.",
            hints: [
              "Cloud Run with min-instances=0 for cold start trade-off",
              "Cloud CDN for cacheable inference responses",
              "Model warming strategies to reduce cold start",
              "Pub/Sub + Cloud Run for async heavy workloads",
            ],
          },
        },
      ],
    },
    {
      id: "phase-3",
      title: "Phase 3: Distributed Systems & Kafka",
      color: "#f59e0b",
      weeks: "9–12",
      modules: [
        {
          id: "m8",
          title: "Microservices Architecture",
          week: "Week 9–10",
          icon: "🏗️",
          duration: "2 weeks",
          description: "Design, build, and operate distributed microservices systems.",
          topics: [
            "Microservices vs monolith — trade-offs, Conway's Law",
            "Service decomposition patterns (domain-driven design, bounded contexts)",
            "Inter-service communication: REST, gRPC, async messaging",
            "gRPC: protobuf, streaming, when to prefer over REST",
            "API Gateway pattern (Kong, AWS API Gateway, Cloud Endpoints)",
            "Service discovery: DNS-based, client-side (Consul)",
            "Distributed tracing: OpenTelemetry, Jaeger, Cloud Trace",
            "Circuit breakers, retries, timeouts (resilience patterns)",
            "Saga pattern for distributed transactions",
          ],
          labs: [
            {
              title: "gRPC Service in Python",
              desc: "Define a .proto for an inference service. Implement server + client in Python. Benchmark vs REST.",
              difficulty: "intermediate",
            },
            {
              title: "Distributed Tracing",
              desc: "Add OpenTelemetry instrumentation to two FastAPI services. Propagate trace context between them. Visualize in Jaeger.",
              difficulty: "advanced",
            },
            {
              title: "Circuit Breaker with Tenacity",
              desc: "Use the tenacity library to add retry + exponential backoff + circuit breaker to service-to-service calls.",
              difficulty: "intermediate",
            },
          ],
          resources: [
            { title: "microservices.io Patterns", url: "https://microservices.io/patterns/" },
            { title: "gRPC Python Tutorial", url: "https://grpc.io/docs/languages/python/basics/" },
            { title: "OpenTelemetry Python", url: "https://opentelemetry.io/docs/languages/python/" },
          ],
          interviewQuestions: [
            "When would you NOT use microservices?",
            "How do you handle distributed transactions? Explain the Saga pattern.",
            "What is a circuit breaker and when does it open?",
            "How does gRPC differ from REST? When would you pick gRPC?",
            "How do you debug a latency issue in a distributed system?",
          ],
          systemDesign: {
            prompt: "Design the backend for an AI-powered document processing pipeline with 5 microservices: upload, OCR, classification, embedding, and search.",
            hints: [
              "Async messaging between stages (Kafka)",
              "Object storage (S3/GCS) for passing large documents between services",
              "Idempotent processing with message deduplication",
              "Dead letter queues for failed documents",
            ],
          },
        },
        {
          id: "m9",
          title: "Kafka & Message Queues",
          week: "Week 11–12",
          icon: "📨",
          duration: "2 weeks",
          description: "Build event-driven systems with Kafka — the backbone of real-time data pipelines.",
          topics: [
            "Event-driven architecture: events vs commands vs queries",
            "Kafka architecture: brokers, topics, partitions, offsets, consumer groups",
            "Producer patterns: acks, compression, batching, idempotent producers",
            "Consumer patterns: at-least-once, at-most-once, exactly-once semantics",
            "Schema Registry + Avro/Protobuf for schema evolution",
            "Kafka Streams and KSQL for stream processing",
            "Kafka Connect for CDC (change data capture) from PostgreSQL",
            "Dead letter queues, error handling, retry topics",
            "Kafka in Kubernetes (Strimzi operator)",
          ],
          labs: [
            {
              title: "Event-Driven AI Pipeline",
              desc: "Build a pipeline: upload image → Kafka topic → consumer embeds with CLIP → stores in vector DB. Handle failures with a dead letter topic.",
              difficulty: "advanced",
            },
            {
              title: "CDC with Debezium",
              desc: "Set up Debezium to capture changes from PostgreSQL and stream them to Kafka. Build a consumer that maintains a read-optimized MongoDB view.",
              difficulty: "advanced",
            },
            {
              title: "Consumer Group Rebalancing",
              desc: "Run 3 consumers in a group. Kill one. Observe partition rebalancing. Measure lag with kafka-consumer-groups.sh.",
              difficulty: "intermediate",
            },
          ],
          resources: [
            { title: "Confluent Kafka Tutorials (Free)", url: "https://developer.confluent.io/tutorials/" },
            { title: "Kafka: The Definitive Guide (Free PDF)", url: "https://www.confluent.io/resources/kafka-the-definitive-guide/" },
            { title: "Strimzi Kafka on K8s", url: "https://strimzi.io/" },
          ],
          interviewQuestions: [
            "What is a Kafka partition, and why does partition count matter?",
            "Explain at-least-once vs exactly-once delivery.",
            "How do consumer groups enable horizontal scaling?",
            "What is the difference between Kafka and RabbitMQ?",
            "How does Kafka guarantee ordering?",
            "What is CDC and when would you use Debezium?",
          ],
          systemDesign: {
            prompt: "Design a real-time ML feature pipeline that processes 10M events/day from user behavior, computes features, and serves them to a model with <50ms latency.",
            hints: [
              "Kafka for event ingestion",
              "Kafka Streams / Flink for windowed aggregations",
              "Redis for low-latency feature serving",
              "Feature store (Feast) for consistency between training and serving",
            ],
          },
        },
      ],
    },
    {
      id: "phase-4",
      title: "Phase 4: AI/ML Engineering in Production",
      color: "#10b981",
      weeks: "13–17",
      modules: [
        {
          id: "m10",
          title: "LLMs & AI Serving Frameworks",
          week: "Week 13–14",
          icon: "🤖",
          duration: "2 weeks",
          description: "Deploy and serve LLMs in production — efficiently and reliably.",
          topics: [
            "LLM inference basics: tokens, context window, KV cache",
            "HuggingFace Transformers: loading, pipeline API, tokenizers",
            "Inference optimization: quantization (GPTQ, bitsandbytes, AWQ), batching",
            "Serving frameworks: vLLM, TGI (Text Generation Inference), Ollama, Triton",
            "OpenAI-compatible API with vLLM — drop-in replacement",
            "GPU resource management in Kubernetes (NVIDIA device plugin)",
            "Model packaging: ONNX export, TorchServe",
            "Autoscaling for GPU workloads (KEDA + GPU metrics)",
          ],
          labs: [
            {
              title: "Deploy Llama 3.2 with vLLM",
              desc: "Run vLLM in Docker with a quantized Llama model. Benchmark throughput and latency. Expose an OpenAI-compatible API.",
              difficulty: "advanced",
            },
            {
              title: "HuggingFace Model Server",
              desc: "Serve a sentence-transformer model (for embeddings) behind FastAPI. Add request batching to maximize GPU utilization.",
              difficulty: "intermediate",
            },
            {
              title: "Quantization Comparison",
              desc: "Compare FP16 vs INT8 vs INT4 for a model: measure memory usage, throughput, and output quality.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "vLLM Docs", url: "https://docs.vllm.ai/" },
            { title: "HuggingFace Model Hub", url: "https://huggingface.co/models" },
            { title: "TGI (Text Generation Inference)", url: "https://huggingface.co/docs/text-generation-inference" },
            { title: "NVIDIA Triton Inference Server", url: "https://developer.nvidia.com/triton-inference-server" },
          ],
          interviewQuestions: [
            "What is KV cache and how does it speed up LLM inference?",
            "Explain quantization. What are the trade-offs of INT4 vs FP16?",
            "What is continuous batching and why does vLLM use it?",
            "How would you serve a 70B parameter model cost-efficiently?",
            "How do you scale GPU workloads in Kubernetes?",
          ],
          systemDesign: {
            prompt: "Design an LLM serving platform that serves 5 different models to 10k users with SLA of p99 < 2s. Budget: $5k/month.",
            hints: [
              "Shared GPU cluster with model multiplexing",
              "Request routing by model name",
              "Spot instances for batch/offline, reserved for realtime",
              "Response caching for common prompts (semantic cache with Redis)",
            ],
          },
        },
        {
          id: "m11",
          title: "RAG, LangChain & Vector Databases",
          week: "Week 15",
          icon: "🔍",
          duration: "1.5 weeks",
          description: "Build production RAG systems — the most common real-world LLM application.",
          topics: [
            "RAG architecture: retrieval → augmentation → generation",
            "Embedding models: sentence-transformers, OpenAI ada-002, Cohere",
            "Vector databases: pgvector, Pinecone, Weaviate, Qdrant, Chroma",
            "Chunking strategies: fixed, semantic, hierarchical, late chunking",
            "LangChain: chains, retrievers, memory, LCEL",
            "Advanced RAG: re-ranking (Cohere, Cross-encoder), HyDE, multi-query",
            "RAG evaluation: RAGAs framework (faithfulness, relevance, completeness)",
            "LangSmith for tracing and debugging LLM chains",
          ],
          labs: [
            {
              title: "Build a Document Q&A System",
              desc: "Ingest PDFs → chunk → embed → store in Qdrant → query with LangChain + LLM. Deploy as a FastAPI endpoint.",
              difficulty: "intermediate",
            },
            {
              title: "RAG Evaluation Pipeline",
              desc: "Build a RAGAs evaluation pipeline. Measure faithfulness and answer relevance. A/B test two chunking strategies.",
              difficulty: "advanced",
            },
            {
              title: "Semantic Cache with Redis",
              desc: "Cache LLM responses using vector similarity. If a query is >90% similar to a cached query, return the cached response.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "LangChain Docs", url: "https://python.langchain.com/docs/introduction/" },
            { title: "LlamaIndex Docs", url: "https://docs.llamaindex.ai/" },
            { title: "Qdrant Docs", url: "https://qdrant.tech/documentation/" },
            { title: "RAGAs Framework", url: "https://docs.ragas.io/" },
          ],
          interviewQuestions: [
            "Explain the RAG pipeline end to end.",
            "What are the failure modes of RAG? How do you evaluate it?",
            "What chunking strategy would you use for legal documents?",
            "When would you use pgvector vs a dedicated vector DB like Pinecone?",
            "What is re-ranking and when does it improve retrieval?",
            "How do you handle a RAG system that hallucinates?",
          ],
          systemDesign: {
            prompt: "Design a multi-tenant RAG platform for a SaaS product where each customer has their own document corpus. 1000 customers, 100K docs each.",
            hints: [
              "Namespace isolation in Qdrant/Pinecone per tenant",
              "Async ingestion pipeline (Kafka → embedding worker → vector DB)",
              "Metadata filtering to prevent cross-tenant data leaks",
              "Cost model: embedding only once, re-rank at query time",
            ],
          },
        },
        {
          id: "m12",
          title: "Agentic AI: LangGraph, AutoGen, ADK",
          week: "Week 16",
          icon: "🕸️",
          duration: "1 week",
          description: "Build stateful, multi-step AI agents that can use tools and collaborate.",
          topics: [
            "Agentic patterns: ReAct, Plan-and-Execute, reflection loops",
            "LangGraph: nodes, edges, state machines, checkpointing",
            "Tool use: function calling, structured output, tool schemas",
            "Multi-agent systems: orchestrator-agent pattern, role-based agents",
            "AutoGen: conversational agents, group chat, code execution",
            "Google ADK (Agent Development Kit)",
            "Agent memory: short-term (context), long-term (vector store), episodic",
            "Production challenges: non-determinism, infinite loops, cost control",
          ],
          labs: [
            {
              title: "LangGraph Research Agent",
              desc: "Build a research agent with tools: web search, document retrieval, calculator. Use LangGraph for state management and a human-in-the-loop interrupt.",
              difficulty: "advanced",
            },
            {
              title: "Multi-Agent Code Review",
              desc: "Use AutoGen to build a multi-agent system: Planner + Coder + Reviewer agents that collaborate on writing and testing code.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "LangGraph Docs", url: "https://langchain-ai.github.io/langgraph/" },
            { title: "AutoGen Docs", url: "https://microsoft.github.io/autogen/" },
            { title: "Google ADK", url: "https://google.github.io/adk-docs/" },
          ],
          interviewQuestions: [
            "What is the difference between a chain and an agent?",
            "How does LangGraph differ from LangChain?",
            "How do you prevent an agent from looping infinitely?",
            "What is human-in-the-loop and when would you add it to an agent?",
            "How would you test an agentic system?",
            "How do you control costs in a multi-agent system?",
          ],
          systemDesign: {
            prompt: "Design an AI coding assistant agent that can read a codebase, understand issues, write fixes, run tests, and create PRs — autonomously.",
            hints: [
              "Tool use: GitHub API, bash execution sandbox (Docker), test runner",
              "LangGraph for the state machine (plan → code → test → review → PR)",
              "Human approval step before PR creation",
              "Sandboxed code execution to prevent escapes",
            ],
          },
        },
        {
          id: "m13",
          title: "AI Observability & Monitoring",
          week: "Week 17",
          icon: "📊",
          duration: "1 week",
          description: "Monitor ML models in production — detect drift, measure quality, control costs.",
          topics: [
            "Prometheus + Grafana: metrics collection, dashboards, alerting",
            "LLM-specific metrics: tokens/sec, latency percentiles, error rate, cost/request",
            "LangSmith / Langfuse for LLM tracing and evaluation",
            "Model drift detection: input drift, output drift, concept drift",
            "Structured logging with structlog / loguru",
            "Alerting: PagerDuty, OpsGenie integrations",
            "Cost monitoring: OpenAI API spend tracking, GPU utilization",
            "A/B testing infrastructure for model versions",
          ],
          labs: [
            {
              title: "Prometheus + Grafana Stack",
              desc: "Deploy kube-prometheus-stack with Helm. Instrument your FastAPI app with custom metrics (inference latency, token count). Build a Grafana dashboard.",
              difficulty: "intermediate",
            },
            {
              title: "LLM Observability with Langfuse",
              desc: "Integrate Langfuse into a LangChain RAG pipeline. Track traces, scores, and costs per session. Set up a dashboard.",
              difficulty: "intermediate",
            },
          ],
          resources: [
            { title: "Prometheus Docs", url: "https://prometheus.io/docs/" },
            { title: "Grafana Docs", url: "https://grafana.com/docs/" },
            { title: "Langfuse (Open Source LLM Observability)", url: "https://langfuse.com/" },
          ],
          interviewQuestions: [
            "What metrics would you track for an LLM in production?",
            "How do you detect model drift?",
            "Explain the difference between structured logs, metrics, and traces.",
            "How would you set up alerting for a degrading RAG system?",
          ],
          systemDesign: null,
        },
      ],
    },
    {
      id: "phase-5",
      title: "Phase 5: System Design & Interview Prep",
      color: "#ef4444",
      weeks: "18–20",
      modules: [
        {
          id: "m14",
          title: "Large-Scale System Design",
          week: "Week 18–19",
          icon: "📐",
          duration: "2 weeks",
          description: "Practice designing production systems end-to-end — the final boss of engineering interviews.",
          topics: [
            "System design framework: requirements → scale → API → data model → high-level → deep dive",
            "Back-of-envelope estimation: QPS, storage, bandwidth, latency",
            "Scalability patterns: horizontal scaling, read replicas, caching, CDN, sharding",
            "Availability patterns: redundancy, failover, circuit breakers, graceful degradation",
            "Data consistency models: strong, eventual, causal consistency",
            "Designing for idempotency and exactly-once processing",
            "Rate limiting algorithms: token bucket, leaky bucket, fixed/sliding window",
            "Common system design problems with AI components",
          ],
          labs: [
            {
              title: "Design an AI Feature Store",
              desc: "Design and partially implement a feature store that serves ML features with <10ms latency. Handle both batch and realtime feature computation.",
              difficulty: "advanced",
            },
            {
              title: "Design a Chat Application with AI",
              desc: "Design WhatsApp-scale chat (2B users) with an AI assistant embedded. Cover: messaging, presence, push notifications, AI response generation.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "System Design Primer (GitHub)", url: "https://github.com/donnemartin/system-design-primer" },
            { title: "ByteByteGo Blog", url: "https://blog.bytebytego.com/" },
            { title: "Designing Data-Intensive Applications (Book)", url: "https://dataintensive.net/" },
          ],
          interviewQuestions: [
            "Design YouTube",
            "Design a URL shortener",
            "Design a notification system",
            "Design a rate limiter",
            "Design Twitter's feed",
            "Design a vector search system for 1B vectors",
            "Design an LLM-powered customer support system",
          ],
          systemDesign: {
            prompt: "Design an internal AI platform for a company of 500 engineers. It must support: RAG over internal docs, code generation, and model fine-tuning jobs.",
            hints: [
              "Self-hosted models on GPU cluster (cost control)",
              "Multi-tenant with usage quotas per team",
              "Fine-tuning job queue (Kubernetes Jobs + Argo Workflows)",
              "Model registry (MLflow) and promotion pipeline",
            ],
          },
        },
        {
          id: "m15",
          title: "Interview Preparation",
          week: "Week 20",
          icon: "🎯",
          duration: "1 week",
          description: "Polish your skills, build your portfolio, and ace technical interviews.",
          topics: [
            "Coding interviews: data structures, algorithms (LeetCode Mediums)",
            "API design interviews: REST conventions, versioning, pagination",
            "Architecture walkthroughs: presenting your own projects",
            "Behavioral: STAR method for engineering leadership questions",
            "Live system design practice with a timer",
            "Portfolio projects to showcase (at least 2 end-to-end AI features)",
          ],
          labs: [
            {
              title: "End-to-End Capstone: AI SaaS Platform",
              desc: "Build and deploy a complete AI-powered SaaS: FastAPI + PostgreSQL + Redis + Kafka + Docker + K8s + CI/CD + RAG + monitoring. Present it as your portfolio project.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "LeetCode (Mediums)", url: "https://leetcode.com/problemset/all/?difficulty=MEDIUM" },
            { title: "Pramp (Mock Interviews)", url: "https://www.pramp.com/" },
            { title: "interviewing.io", url: "https://interviewing.io/" },
          ],
          interviewQuestions: [
            "Tell me about a time you had to make a critical architectural decision under pressure.",
            "How would you mentor a junior engineer learning distributed systems?",
            "Describe an AI feature you took from prototype to production.",
            "How do you decide when a prototype is ready for production?",
          ],
          systemDesign: null,
        },
      ],
    },
  ],
};

if (typeof module !== "undefined") module.exports = CURRICULUM;
