const CURRICULUM = {
  title: "AI Backend Engineer Mastery",
  subtitle: "Docker → Kubernetes → Cloud → AI/ML Production Systems",
  totalWeeks: 20,
  phases: [
    {
      id: "phase-1",
      title: "Phase 1: Containerization & Backend Foundations",
      color: "#3b82f6",
      weeks: "1–4",
      modules: [
        {
          id: "m1",
          title: "Docker Deep Dive",
          week: "Week 1–2",
          icon: "🐳",
          duration: "2 weeks",
          description: "Master containerization — the foundation of everything else in this curriculum.",
          topics: [
            "What is Docker? VMs vs containers",
            "Images, layers, Dockerfile authoring",
            "docker build, run, exec, logs, inspect",
            "Volumes, bind mounts, networking (bridge, host, overlay)",
            "Docker Compose — multi-container apps",
            "Multi-stage builds for lean production images",
            "Docker registries (Docker Hub, ECR, GCR, Artifact Registry)",
            "Security: non-root users, read-only filesystems, image scanning (Trivy)",
          ],
          labs: [
            {
              title: "Containerize a FastAPI App",
              desc: "Write a Dockerfile for a Python FastAPI app. Use multi-stage build to keep the image small. Push to Docker Hub.",
              difficulty: "beginner",
            },
            {
              title: "Multi-Service Compose Stack",
              desc: "Spin up FastAPI + PostgreSQL + Redis using Docker Compose with named volumes, health checks, and a custom network.",
              difficulty: "intermediate",
            },
            {
              title: "Image Security Audit",
              desc: "Scan your images with Trivy. Reduce CVEs by switching base images and using non-root users.",
              difficulty: "intermediate",
            },
          ],
          resources: [
            { title: "Docker Official Docs", url: "https://docs.docker.com/get-started/" },
            { title: "Play with Docker (free sandbox)", url: "https://labs.play-with-docker.com/" },
            { title: "Dockerfile Best Practices", url: "https://docs.docker.com/develop/develop-images/dockerfile_best-practices/" },
            { title: "Trivy — Image Scanner", url: "https://github.com/aquasecurity/trivy" },
          ],
          interviewQuestions: [
            "What is the difference between CMD and ENTRYPOINT?",
            "How do Docker layers work, and why does layer caching matter for CI?",
            "Explain the difference between COPY and ADD.",
            "How would you reduce Docker image size for a Python app?",
            "What's the difference between bridge, host, and overlay networks?",
            "How do you share secrets securely in Docker? (not ENV variables)",
          ],
          systemDesign: null,
        },
        {
          id: "m2",
          title: "Python + FastAPI for Production",
          week: "Week 2–3",
          icon: "⚡",
          duration: "2 weeks",
          description: "Build production-grade async APIs with FastAPI — the dominant Python backend framework in AI engineering.",
          topics: [
            "Async Python: event loop, async/await, asyncio",
            "FastAPI fundamentals: routes, Pydantic models, dependency injection",
            "Middleware: CORS, rate limiting, request logging",
            "Background tasks and lifespan events",
            "JWT authentication with OAuth2",
            "OpenAPI docs, versioning, structured error handling",
            "Testing: pytest, httpx AsyncClient, mocking",
            "Production: Uvicorn + Gunicorn workers, health check endpoints",
          ],
          labs: [
            {
              title: "Build a URL Shortener API",
              desc: "FastAPI + PostgreSQL + Redis for caching. Include auth, pagination, and a /health endpoint. Containerize it.",
              difficulty: "beginner",
            },
            {
              title: "Rate-Limited AI Inference API",
              desc: "Wrap a HuggingFace model behind a FastAPI endpoint. Add Redis-based rate limiting per API key.",
              difficulty: "intermediate",
            },
            {
              title: "Background Job Queue",
              desc: "Use FastAPI BackgroundTasks + Celery + Redis to process long-running tasks asynchronously.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "FastAPI Official Docs", url: "https://fastapi.tiangolo.com/" },
            { title: "Pydantic v2 Docs", url: "https://docs.pydantic.dev/latest/" },
            { title: "Async Python for Beginners", url: "https://realpython.com/async-io-python/" },
            { title: "FastAPI Best Practices (GitHub)", url: "https://github.com/zhanymkanov/fastapi-best-practices" },
          ],
          interviewQuestions: [
            "How does FastAPI's dependency injection work?",
            "What's the difference between async def and def in FastAPI?",
            "How would you implement API versioning?",
            "How do you handle long-running tasks without blocking the event loop?",
            "Explain Pydantic's role in request validation.",
            "How do you write integration tests for a FastAPI app that uses a real DB?",
          ],
          systemDesign: null,
        },
        {
          id: "m3",
          title: "Databases: PostgreSQL, MongoDB, Redis",
          week: "Week 3–4",
          icon: "🗄️",
          duration: "2 weeks",
          description: "Master the three database types you'll use in every production system.",
          topics: [
            "PostgreSQL: transactions, ACID, indexes (B-tree, GIN, partial), EXPLAIN ANALYZE",
            "SQLAlchemy async ORM + Alembic migrations",
            "Connection pooling (PgBouncer, asyncpg pools)",
            "MongoDB: document model, aggregation pipeline, Atlas Search",
            "Redis: data structures (string, list, set, sorted set, hash, stream)",
            "Redis patterns: caching, session store, pub/sub, distributed locks, rate limiting",
            "Database design: normalization vs denormalization, sharding strategies",
            "Read replicas and write-ahead logs",
          ],
          labs: [
            {
              title: "PostgreSQL Query Optimization",
              desc: "Load 1M rows of e-commerce data. Write slow queries, use EXPLAIN ANALYZE, add the right indexes, measure improvement.",
              difficulty: "intermediate",
            },
            {
              title: "Redis Caching Layer",
              desc: "Add Redis caching to your FastAPI app with cache invalidation logic. Implement a distributed lock for a shared resource.",
              difficulty: "intermediate",
            },
            {
              title: "MongoDB Aggregation Pipeline",
              desc: "Design a log analytics pipeline using MongoDB aggregation. Group, filter, and compute metrics from raw event documents.",
              difficulty: "intermediate",
            },
          ],
          resources: [
            { title: "PostgreSQL Tutorial", url: "https://www.postgresqltutorial.com/" },
            { title: "Use The Index, Luke!", url: "https://use-the-index-luke.com/" },
            { title: "Redis University (Free)", url: "https://university.redis.com/" },
            { title: "MongoDB University (Free)", url: "https://university.mongodb.com/" },
          ],
          interviewQuestions: [
            "When would you choose MongoDB over PostgreSQL?",
            "What is a database index? Explain B-tree vs GIN.",
            "How does Redis handle persistence (RDB vs AOF)?",
            "What is connection pooling and why does it matter?",
            "Explain the CAP theorem with examples.",
            "How do you implement optimistic vs pessimistic locking?",
          ],
          systemDesign: null,
        },
      ],
    },
    {
      id: "phase-2",
      title: "Phase 2: Kubernetes & Cloud Infrastructure",
      color: "#8b5cf6",
      weeks: "5–8",
      modules: [
        {
          id: "m4",
          title: "Kubernetes Fundamentals",
          week: "Week 5–6",
          icon: "☸️",
          duration: "2 weeks",
          description: "Kubernetes is the operating system of the cloud. Learn to run, scale, and manage containerized workloads.",
          topics: [
            "Architecture: control plane (API server, etcd, scheduler, controller manager) vs worker nodes (kubelet, kube-proxy, container runtime)",
            "Core objects: Pod, Deployment, ReplicaSet, Service (ClusterIP, NodePort, LoadBalancer), Namespace",
            "kubectl: apply, get, describe, logs, exec, port-forward, top",
            "ConfigMaps and Secrets (sealed secrets, External Secrets Operator)",
            "Persistent Volumes (PV), PVCs, StorageClasses",
            "Resource requests and limits, QoS classes",
            "Health checks: liveness, readiness, startup probes",
            "Rolling updates, rollbacks, deployment strategies (RollingUpdate, Recreate, blue-green, canary)",
          ],
          labs: [
            {
              title: "Deploy FastAPI to Kubernetes",
              desc: "Write Deployment + Service + ConfigMap YAMLs. Deploy your Dockerized FastAPI app to a local cluster (minikube or kind). Expose it with a Service.",
              difficulty: "beginner",
            },
            {
              title: "Horizontal Pod Autoscaling",
              desc: "Configure HPA based on CPU/memory. Load test with k6 and watch pods scale up and down.",
              difficulty: "intermediate",
            },
            {
              title: "Zero-Downtime Rolling Deploy",
              desc: "Configure maxUnavailable/maxSurge. Simulate a rolling update and verify zero downtime with a continuous curl loop.",
              difficulty: "intermediate",
            },
          ],
          resources: [
            { title: "Kubernetes Official Docs", url: "https://kubernetes.io/docs/home/" },
            { title: "Killercoda K8s Playground (Free)", url: "https://killercoda.com/playgrounds/scenario/kubernetes" },
            { title: "K8s the Hard Way (Kelsey Hightower)", url: "https://github.com/kelseyhightower/kubernetes-the-hard-way" },
            { title: "kubectl Cheat Sheet", url: "https://kubernetes.io/docs/reference/kubectl/cheatsheet/" },
          ],
          interviewQuestions: [
            "What happens when you run `kubectl apply -f deployment.yaml`?",
            "Explain the difference between a Pod and a Deployment.",
            "How does a Service route traffic to Pods?",
            "What is the difference between liveness and readiness probes?",
            "How would you debug a CrashLoopBackOff?",
            "Explain resource requests vs limits. What is a QoS class?",
          ],
          systemDesign: {
            prompt: "Design a Kubernetes deployment for a high-traffic FastAPI service that processes AI inference requests. The service must autoscale, have zero-downtime deploys, and expose metrics.",
            hints: [
              "HPA + custom metrics (KEDA for queue-based scaling)",
              "PodDisruptionBudget for availability during upgrades",
              "Readiness probe to hold traffic until model is loaded",
              "Prometheus ServiceMonitor for scraping",
            ],
          },
        },
        {
          id: "m5",
          title: "Kubernetes Advanced: Networking, Storage, Security",
          week: "Week 6–7",
          icon: "🔧",
          duration: "1.5 weeks",
          description: "Go beyond basics — learn production patterns for networking, storage, RBAC, and multi-tenancy.",
          topics: [
            "Ingress controllers (NGINX, Traefik) and IngressClass",
            "Network policies — default deny, allow specific flows",
            "Service mesh basics (Istio/Linkerd): mTLS, traffic splitting, observability",
            "StatefulSets: stable network identity, ordered scaling (for databases, Kafka)",
            "DaemonSets (log agents, node exporters)",
            "RBAC: Role, ClusterRole, RoleBinding, ServiceAccounts",
            "Pod Security Standards / OPA Gatekeeper",
            "Multi-tenancy: namespaces, resource quotas, LimitRanges",
          ],
          labs: [
            {
              title: "Ingress with TLS",
              desc: "Set up NGINX Ingress Controller. Configure cert-manager with Let's Encrypt for automatic TLS. Route traffic to two different services by path.",
              difficulty: "intermediate",
            },
            {
              title: "Network Policy: Zero Trust",
              desc: "Implement a default-deny NetworkPolicy. Explicitly allow: frontend→API, API→DB, monitoring→all. Verify with kubectl exec tests.",
              difficulty: "advanced",
            },
            {
              title: "StatefulSet for PostgreSQL",
              desc: "Deploy PostgreSQL as a StatefulSet with a PVC per replica. Test pod deletion and observe stable identity recovery.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "Network Policies Explained", url: "https://kubernetes.io/docs/concepts/services-networking/network-policies/" },
            { title: "Ingress Controllers Comparison", url: "https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/" },
            { title: "RBAC Deep Dive", url: "https://kubernetes.io/docs/reference/access-authn-authz/rbac/" },
          ],
          interviewQuestions: [
            "How does Kubernetes networking work? What is CNI?",
            "When would you use a StatefulSet vs a Deployment?",
            "Explain RBAC. How do you give a pod access to Kubernetes API?",
            "What is a network policy, and how does it differ from a firewall rule?",
            "How does cert-manager automate TLS certificate management?",
          ],
          systemDesign: null,
        },
        {
          id: "m6",
          title: "CI/CD Pipelines",
          week: "Week 7",
          icon: "🔄",
          duration: "1 week",
          description: "Automate the full path from code to production.",
          topics: [
            "CI/CD concepts: continuous integration vs delivery vs deployment",
            "GitHub Actions: workflows, jobs, steps, secrets, matrix builds",
            "Docker image build + push in CI",
            "GitOps with ArgoCD: sync from git to cluster",
            "Helm: charts, values, templating, releases",
            "Kustomize: overlays for dev/staging/prod",
            "Canary deployments with Argo Rollouts",
            "Security: SAST, container image scanning in pipeline",
          ],
          labs: [
            {
              title: "GitHub Actions Pipeline",
              desc: "Build a pipeline: test → lint → docker build → push to registry → update K8s deployment. Trigger on PR and main branch push.",
              difficulty: "intermediate",
            },
            {
              title: "ArgoCD GitOps Setup",
              desc: "Install ArgoCD. Create an Application manifest pointing to your Helm chart in git. Push a change and watch ArgoCD sync it.",
              difficulty: "intermediate",
            },
            {
              title: "Helm Chart from Scratch",
              desc: "Package your FastAPI app as a Helm chart with configurable replicas, image tag, resource limits, and ingress toggle.",
              difficulty: "intermediate",
            },
          ],
          resources: [
            { title: "GitHub Actions Docs", url: "https://docs.github.com/en/actions" },
            { title: "ArgoCD Getting Started", url: "https://argo-cd.readthedocs.io/en/stable/getting_started/" },
            { title: "Helm Docs", url: "https://helm.sh/docs/" },
          ],
          interviewQuestions: [
            "What is the difference between CI and CD?",
            "What is GitOps and how does ArgoCD implement it?",
            "How do you safely roll back a bad deployment?",
            "What is Helm? When would you use Kustomize instead?",
            "How do you handle secrets in CI/CD pipelines?",
          ],
          systemDesign: null,
        },
        {
          id: "m7",
          title: "Cloud Platforms: GCP / AWS / Azure",
          week: "Week 8",
          icon: "☁️",
          duration: "1 week",
          description: "Learn the core cloud primitives you'll use in every production system.",
          topics: [
            "Compute: Cloud Run, Lambda, EC2, GCE, App Engine",
            "Storage: S3/GCS/Azure Blob, EBS/persistent disks",
            "Managed K8s: GKE, EKS, AKS — differences, autopilot vs standard",
            "IAM: roles, service accounts, workload identity",
            "Networking: VPC, subnets, NAT, load balancers, Cloud CDN",
            "Serverless: Cloud Run (GCP), Lambda (AWS), Container Apps (Azure)",
            "Cloud Functions vs Cloud Run — when to use each",
            "Cost management: spot/preemptible instances, committed use discounts",
          ],
          labs: [
            {
              title: "Deploy to Cloud Run",
              desc: "Push your FastAPI image to Google Artifact Registry. Deploy to Cloud Run with auto-scaling min=0. Add a custom domain.",
              difficulty: "beginner",
            },
            {
              title: "GKE Autopilot Cluster",
              desc: "Create a GKE Autopilot cluster. Deploy your app via Helm. Set up Workload Identity to access GCS from a pod.",
              difficulty: "intermediate",
            },
            {
              title: "IAM Least Privilege",
              desc: "Audit an over-permissioned service account. Create a custom IAM role with only the permissions needed. Verify access.",
              difficulty: "intermediate",
            },
          ],
          resources: [
            { title: "GCP Free Tier", url: "https://cloud.google.com/free" },
            { title: "AWS Free Tier", url: "https://aws.amazon.com/free/" },
            { title: "Cloud Run Quickstart", url: "https://cloud.google.com/run/docs/quickstarts" },
            { title: "GCP Architecture Center", url: "https://cloud.google.com/architecture" },
          ],
          interviewQuestions: [
            "When would you use Cloud Run vs GKE vs Cloud Functions?",
            "Explain IAM roles vs service accounts.",
            "What is Workload Identity and why is it better than service account keys?",
            "How does an Application Load Balancer differ from a Network Load Balancer?",
            "What are spot/preemptible instances and when would you use them for AI workloads?",
          ],
          systemDesign: {
            prompt: "Design a serverless AI inference system that costs near-zero when idle but handles burst traffic of 1000 req/s.",
            hints: [
              "Cloud Run with min-instances=0 for cold start trade-off",
              "Cloud CDN for cacheable inference responses",
              "Model warming strategies to reduce cold start",
              "Pub/Sub + Cloud Run for async heavy workloads",
            ],
          },
        },
      ],
    },
    {
      id: "phase-3",
      title: "Phase 3: Distributed Systems & Kafka",
      color: "#f59e0b",
      weeks: "9–12",
      modules: [
        {
          id: "m8",
          title: "Microservices Architecture",
          week: "Week 9–10",
          icon: "🏗️",
          duration: "2 weeks",
          description: "Design, build, and operate distributed microservices systems.",
          topics: [
            "Microservices vs monolith — trade-offs, Conway's Law",
            "Service decomposition patterns (domain-driven design, bounded contexts)",
            "Inter-service communication: REST, gRPC, async messaging",
            "gRPC: protobuf, streaming, when to prefer over REST",
            "API Gateway pattern (Kong, AWS API Gateway, Cloud Endpoints)",
            "Service discovery: DNS-based, client-side (Consul)",
            "Distributed tracing: OpenTelemetry, Jaeger, Cloud Trace",
            "Circuit breakers, retries, timeouts (resilience patterns)",
            "Saga pattern for distributed transactions",
          ],
          labs: [
            {
              title: "gRPC Service in Python",
              desc: "Define a .proto for an inference service. Implement server + client in Python. Benchmark vs REST.",
              difficulty: "intermediate",
            },
            {
              title: "Distributed Tracing",
              desc: "Add OpenTelemetry instrumentation to two FastAPI services. Propagate trace context between them. Visualize in Jaeger.",
              difficulty: "advanced",
            },
            {
              title: "Circuit Breaker with Tenacity",
              desc: "Use the tenacity library to add retry + exponential backoff + circuit breaker to service-to-service calls.",
              difficulty: "intermediate",
            },
          ],
          resources: [
            { title: "microservices.io Patterns", url: "https://microservices.io/patterns/" },
            { title: "gRPC Python Tutorial", url: "https://grpc.io/docs/languages/python/basics/" },
            { title: "OpenTelemetry Python", url: "https://opentelemetry.io/docs/languages/python/" },
          ],
          interviewQuestions: [
            "When would you NOT use microservices?",
            "How do you handle distributed transactions? Explain the Saga pattern.",
            "What is a circuit breaker and when does it open?",
            "How does gRPC differ from REST? When would you pick gRPC?",
            "How do you debug a latency issue in a distributed system?",
          ],
          systemDesign: {
            prompt: "Design the backend for an AI-powered document processing pipeline with 5 microservices: upload, OCR, classification, embedding, and search.",
            hints: [
              "Async messaging between stages (Kafka)",
              "Object storage (S3/GCS) for passing large documents between services",
              "Idempotent processing with message deduplication",
              "Dead letter queues for failed documents",
            ],
          },
        },
        {
          id: "m9",
          title: "Kafka & Message Queues",
          week: "Week 11–12",
          icon: "📨",
          duration: "2 weeks",
          description: "Build event-driven systems with Kafka — the backbone of real-time data pipelines.",
          topics: [
            // Architecture
            "Event-driven architecture: events vs commands vs queries (CQRS)",
            "Kafka architecture: brokers, topics, partitions, offsets, consumer groups",
            "KRaft mode: Kafka without ZooKeeper — controller quorum, metadata topic, leader election",
            "Log retention: time-based, size-based, and compacted topics — when to use each",
            "Partition internals: leader/follower, ISR (in-sync replicas), replica lag",
            "Replication: replication factor, min.insync.replicas, unclean leader election",
            // Producers
            "Producer acks: acks=0, acks=1, acks=all — durability vs latency trade-offs",
            "Idempotent producers: enable.idempotence, sequence numbers, deduplication",
            "Kafka transactions: transactional.id, begin/commit/abort, atomic multi-topic writes",
            "Producer batching: linger.ms, batch.size, compression.type (lz4, zstd, snappy)",
            "Partitioner: murmur2 hash by key, sticky partitioner for null keys",
            // Consumers
            "Consumer offset management: at-least-once, at-most-once, exactly-once semantics",
            "Consumer groups: partition assignment, one consumer per partition per group",
            "Partition assignors: RangeAssignor, RoundRobinAssignor, StickyAssignor, CooperativeStickyAssignor",
            "Consumer group rebalancing: stop-the-world vs incremental (cooperative) rebalancing",
            "Consumer lag: definition, monitoring with kafka-consumer-groups.sh, Prometheus JMX exporter",
            "Offset reset strategies: --to-earliest, --to-latest, --to-datetime, --to-offset",
            // Schema Registry
            "Schema Registry: purpose, subject naming strategies, magic byte + schema ID in messages",
            "Avro vs Protobuf vs JSON Schema: size, evolution support, ecosystem fit",
            "Schema compatibility modes: BACKWARD, FORWARD, FULL, NONE — deploy order implications",
            "Schema evolution rules: safe changes (add optional field), breaking changes (rename, type change)",
            // Stream Processing
            "Kafka Streams concepts: KStream vs KTable vs GlobalKTable",
            "Windowing: tumbling, hopping, session windows — event time vs processing time",
            "Watermarks and late-arriving events: acceptable lateness, grace periods",
            "Kafka Streams state stores: RocksDB, changelog topics, state restoration on restart",
            "ksqlDB: CREATE STREAM, CREATE TABLE, EMIT CHANGES vs EMIT FINAL, pull vs push queries",
            "Faust: Python Kafka Streams — agents, tables, windowed aggregations",
            // Kafka Connect & CDC
            "Kafka Connect: source vs sink connectors, workers, tasks, SMTs (Single Message Transforms)",
            "Debezium: WAL-based CDC, replication slots, publication tables, before/after snapshots",
            "Outbox pattern: atomic business write + event publish in one DB transaction",
            "Dead letter topics (DLT): routing, error headers, retry topics with exponential backoff",
            // Operations
            "Kafka on Kubernetes: Strimzi operator, KafkaNodePool CRD, rolling upgrades",
            "Managed Kafka: Confluent Cloud vs AWS MSK vs self-hosted — trade-offs",
            "Monitoring: consumer lag, under-replicated partitions, ISR shrink rate, broker GC",
            "Security: SASL/SCRAM, mTLS, ACLs per topic/consumer group, Schema Registry auth",
          ],
          labs: [
            {
              title: "Event-Driven RAG Ingestion Pipeline",
              desc: "Build a full pipeline: FastAPI uploads documents → Kafka topic → embedding worker (confluent-kafka + OpenAI) → Qdrant vector store. Handle malformed documents with a dead letter topic. Run 3 worker instances and observe partition distribution.",
              difficulty: "advanced",
            },
            {
              title: "CDC with Debezium + Outbox Pattern",
              desc: "Configure PostgreSQL with wal_level=logical. Register a Debezium connector that reads the outbox_events table. Write a FastAPI endpoint that atomically inserts an order and an outbox event in one DB transaction. Verify the event appears in Kafka within 100ms.",
              difficulty: "advanced",
            },
            {
              title: "Real-Time Feature Pipeline with ksqlDB",
              desc: "Create ksqlDB streams over purchase_events. Build tumbling window aggregations (purchases per user per hour). Join with a user_profiles table for enriched features. Build a pull query endpoint in FastAPI to serve features at <10ms.",
              difficulty: "advanced",
            },
            {
              title: "Consumer Group Rebalancing Experiment",
              desc: "Create a topic with 12 partitions. Start 3 consumers in a group and verify balanced assignment (4 partitions each). Kill one consumer and observe rebalancing with cooperative-sticky. Measure lag buildup during the rebalance window. Compare with stop-the-world rebalancing.",
              difficulty: "intermediate",
            },
            {
              title: "Schema Evolution Without Downtime",
              desc: "Register an Avro schema in Schema Registry. Write events with the v1 schema. Deploy a v2 schema (add optional field). Verify BACKWARD compatibility check passes before registering. Confirm v1 consumers can still read v2 messages (schema resolution).",
              difficulty: "intermediate",
            },
            {
              title: "Exactly-Once with Kafka Transactions",
              desc: "Build a read-process-write loop: consume from input-topic, process (double the value), produce to output-topic using a transactional producer. Simulate a crash mid-transaction. Confirm no duplicate or partial results in the output topic.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "Confluent Kafka Tutorials (Free)", url: "https://developer.confluent.io/tutorials/" },
            { title: "Kafka: The Definitive Guide (Free PDF)", url: "https://www.confluent.io/resources/kafka-the-definitive-guide/" },
            { title: "Strimzi Kafka on K8s", url: "https://strimzi.io/" },
            { title: "Faust: Python Stream Processing", url: "https://faust-streaming.github.io/faust/" },
            { title: "Debezium Documentation", url: "https://debezium.io/documentation/" },
            { title: "ksqlDB Quickstart", url: "https://ksqldb.io/quickstart.html" },
          ],
          interviewQuestions: [
            "What is a Kafka partition, and why does partition count matter for both throughput and ordering?",
            "Explain at-least-once vs exactly-once delivery. How does enable.idempotence differ from Kafka transactions?",
            "How do consumer groups enable horizontal scaling? What happens when you have more consumers than partitions?",
            "What is the difference between Kafka and RabbitMQ? When would you choose each?",
            "How does Kafka guarantee ordering? What is the trade-off between ordering and throughput?",
            "What is acks=all, and why is it not sufficient without min.insync.replicas=2?",
            "Explain the Outbox Pattern. What problem does it solve, and how does Debezium enable it?",
            "What is CDC (Change Data Capture)? How does Debezium read the PostgreSQL WAL without impacting DB performance?",
            "A consumer's processing is slower than production rate. How do you diagnose and fix this?",
            "What is a compacted topic? How does it differ from a regular retained topic? Give a use case.",
            "What is Schema Registry? Why can't you just embed JSON in Kafka messages?",
            "Explain BACKWARD schema compatibility. What changes are safe? What breaks it?",
            "What is the difference between a KStream and a KTable in Kafka Streams?",
            "Explain tumbling vs session windows. Give an example use case for each.",
            "What is consumer lag, and what does sustained high lag tell you about your system?",
            "A message is causing your consumer to crash every time it's retried, blocking the partition. How do you handle it?",
            "What is cooperative sticky rebalancing, and why is it better than the default stop-the-world rebalance?",
            "How would you design a Kafka topic for an AI RAG ingestion pipeline processing 1M documents/day?",
            "Compare Confluent Cloud, AWS MSK, and Strimzi on K8s. When would you choose each?",
            "How do Kafka Streams applications recover state after a crash? What is the role of changelog topics?",
          ],
          systemDesign: {
            prompt: "Design a real-time ML feature pipeline that processes 10M events/day from user behavior, computes features, and serves them to a model with <50ms latency.",
            hints: [
              "Kafka for event ingestion",
              "Kafka Streams / Flink for windowed aggregations",
              "Redis for low-latency feature serving",
              "Feature store (Feast) for consistency between training and serving",
            ],
          },
        },
      ],
    },
    {
      id: "phase-4",
      title: "Phase 4: AI/ML Engineering in Production",
      color: "#10b981",
      weeks: "13–17",
      modules: [
        {
          id: "m10",
          title: "LLMs & AI Serving Frameworks",
          week: "Week 13–14",
          icon: "🤖",
          duration: "2 weeks",
          description: "Deploy and serve LLMs in production — efficiently and reliably.",
          topics: [
            "LLM inference basics: tokens, context window, KV cache",
            "HuggingFace Transformers: loading, pipeline API, tokenizers",
            "Inference optimization: quantization (GPTQ, bitsandbytes, AWQ), batching",
            "Serving frameworks: vLLM, TGI (Text Generation Inference), Ollama, Triton",
            "OpenAI-compatible API with vLLM — drop-in replacement",
            "GPU resource management in Kubernetes (NVIDIA device plugin)",
            "Model packaging: ONNX export, TorchServe",
            "Autoscaling for GPU workloads (KEDA + GPU metrics)",
          ],
          labs: [
            {
              title: "Deploy Llama 3.2 with vLLM",
              desc: "Run vLLM in Docker with a quantized Llama model. Benchmark throughput and latency. Expose an OpenAI-compatible API.",
              difficulty: "advanced",
            },
            {
              title: "HuggingFace Model Server",
              desc: "Serve a sentence-transformer model (for embeddings) behind FastAPI. Add request batching to maximize GPU utilization.",
              difficulty: "intermediate",
            },
            {
              title: "Quantization Comparison",
              desc: "Compare FP16 vs INT8 vs INT4 for a model: measure memory usage, throughput, and output quality.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "vLLM Docs", url: "https://docs.vllm.ai/" },
            { title: "HuggingFace Model Hub", url: "https://huggingface.co/models" },
            { title: "TGI (Text Generation Inference)", url: "https://huggingface.co/docs/text-generation-inference" },
            { title: "NVIDIA Triton Inference Server", url: "https://developer.nvidia.com/triton-inference-server" },
          ],
          interviewQuestions: [
            "What is KV cache and how does it speed up LLM inference?",
            "Explain quantization. What are the trade-offs of INT4 vs FP16?",
            "What is continuous batching and why does vLLM use it?",
            "How would you serve a 70B parameter model cost-efficiently?",
            "How do you scale GPU workloads in Kubernetes?",
          ],
          systemDesign: {
            prompt: "Design an LLM serving platform that serves 5 different models to 10k users with SLA of p99 < 2s. Budget: $5k/month.",
            hints: [
              "Shared GPU cluster with model multiplexing",
              "Request routing by model name",
              "Spot instances for batch/offline, reserved for realtime",
              "Response caching for common prompts (semantic cache with Redis)",
            ],
          },
        },
        {
          id: "m11",
          title: "RAG, LangChain & Vector Databases",
          week: "Week 15",
          icon: "🔍",
          duration: "1.5 weeks",
          description: "Build production RAG systems — the most common real-world LLM application.",
          topics: [
            "RAG architecture: retrieval → augmentation → generation",
            "Embedding models: sentence-transformers, OpenAI ada-002, Cohere",
            "Vector databases: pgvector, Pinecone, Weaviate, Qdrant, Chroma",
            "Chunking strategies: fixed, semantic, hierarchical, late chunking",
            "LangChain: chains, retrievers, memory, LCEL",
            "Advanced RAG: re-ranking (Cohere, Cross-encoder), HyDE, multi-query",
            "RAG evaluation: RAGAs framework (faithfulness, relevance, completeness)",
            "LangSmith for tracing and debugging LLM chains",
          ],
          labs: [
            {
              title: "Build a Document Q&A System",
              desc: "Ingest PDFs → chunk → embed → store in Qdrant → query with LangChain + LLM. Deploy as a FastAPI endpoint.",
              difficulty: "intermediate",
            },
            {
              title: "RAG Evaluation Pipeline",
              desc: "Build a RAGAs evaluation pipeline. Measure faithfulness and answer relevance. A/B test two chunking strategies.",
              difficulty: "advanced",
            },
            {
              title: "Semantic Cache with Redis",
              desc: "Cache LLM responses using vector similarity. If a query is >90% similar to a cached query, return the cached response.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "LangChain Docs", url: "https://python.langchain.com/docs/introduction/" },
            { title: "LlamaIndex Docs", url: "https://docs.llamaindex.ai/" },
            { title: "Qdrant Docs", url: "https://qdrant.tech/documentation/" },
            { title: "RAGAs Framework", url: "https://docs.ragas.io/" },
          ],
          interviewQuestions: [
            "Explain the RAG pipeline end to end.",
            "What are the failure modes of RAG? How do you evaluate it?",
            "What chunking strategy would you use for legal documents?",
            "When would you use pgvector vs a dedicated vector DB like Pinecone?",
            "What is re-ranking and when does it improve retrieval?",
            "How do you handle a RAG system that hallucinates?",
          ],
          systemDesign: {
            prompt: "Design a multi-tenant RAG platform for a SaaS product where each customer has their own document corpus. 1000 customers, 100K docs each.",
            hints: [
              "Namespace isolation in Qdrant/Pinecone per tenant",
              "Async ingestion pipeline (Kafka → embedding worker → vector DB)",
              "Metadata filtering to prevent cross-tenant data leaks",
              "Cost model: embedding only once, re-rank at query time",
            ],
          },
        },
        {
          id: "m12",
          title: "Agentic AI: LangGraph, AutoGen, ADK",
          week: "Week 16",
          icon: "🕸️",
          duration: "1 week",
          description: "Build stateful, multi-step AI agents that can use tools and collaborate.",
          topics: [
            "Agentic patterns: ReAct, Plan-and-Execute, reflection loops",
            "LangGraph: nodes, edges, state machines, checkpointing",
            "Tool use: function calling, structured output, tool schemas",
            "Multi-agent systems: orchestrator-agent pattern, role-based agents",
            "AutoGen: conversational agents, group chat, code execution",
            "Google ADK (Agent Development Kit)",
            "Agent memory: short-term (context), long-term (vector store), episodic",
            "Production challenges: non-determinism, infinite loops, cost control",
          ],
          labs: [
            {
              title: "LangGraph Research Agent",
              desc: "Build a research agent with tools: web search, document retrieval, calculator. Use LangGraph for state management and a human-in-the-loop interrupt.",
              difficulty: "advanced",
            },
            {
              title: "Multi-Agent Code Review",
              desc: "Use AutoGen to build a multi-agent system: Planner + Coder + Reviewer agents that collaborate on writing and testing code.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "LangGraph Docs", url: "https://langchain-ai.github.io/langgraph/" },
            { title: "AutoGen Docs", url: "https://microsoft.github.io/autogen/" },
            { title: "Google ADK", url: "https://google.github.io/adk-docs/" },
          ],
          interviewQuestions: [
            "What is the difference between a chain and an agent?",
            "How does LangGraph differ from LangChain?",
            "How do you prevent an agent from looping infinitely?",
            "What is human-in-the-loop and when would you add it to an agent?",
            "How would you test an agentic system?",
            "How do you control costs in a multi-agent system?",
          ],
          systemDesign: {
            prompt: "Design an AI coding assistant agent that can read a codebase, understand issues, write fixes, run tests, and create PRs — autonomously.",
            hints: [
              "Tool use: GitHub API, bash execution sandbox (Docker), test runner",
              "LangGraph for the state machine (plan → code → test → review → PR)",
              "Human approval step before PR creation",
              "Sandboxed code execution to prevent escapes",
            ],
          },
        },
        {
          id: "m13",
          title: "AI Observability & Monitoring",
          week: "Week 17",
          icon: "📊",
          duration: "1 week",
          description: "Monitor ML models in production — detect drift, measure quality, control costs.",
          topics: [
            "Prometheus + Grafana: metrics collection, dashboards, alerting",
            "LLM-specific metrics: tokens/sec, latency percentiles, error rate, cost/request",
            "LangSmith / Langfuse for LLM tracing and evaluation",
            "Model drift detection: input drift, output drift, concept drift",
            "Structured logging with structlog / loguru",
            "Alerting: PagerDuty, OpsGenie integrations",
            "Cost monitoring: OpenAI API spend tracking, GPU utilization",
            "A/B testing infrastructure for model versions",
          ],
          labs: [
            {
              title: "Prometheus + Grafana Stack",
              desc: "Deploy kube-prometheus-stack with Helm. Instrument your FastAPI app with custom metrics (inference latency, token count). Build a Grafana dashboard.",
              difficulty: "intermediate",
            },
            {
              title: "LLM Observability with Langfuse",
              desc: "Integrate Langfuse into a LangChain RAG pipeline. Track traces, scores, and costs per session. Set up a dashboard.",
              difficulty: "intermediate",
            },
          ],
          resources: [
            { title: "Prometheus Docs", url: "https://prometheus.io/docs/" },
            { title: "Grafana Docs", url: "https://grafana.com/docs/" },
            { title: "Langfuse (Open Source LLM Observability)", url: "https://langfuse.com/" },
          ],
          interviewQuestions: [
            "What metrics would you track for an LLM in production?",
            "How do you detect model drift?",
            "Explain the difference between structured logs, metrics, and traces.",
            "How would you set up alerting for a degrading RAG system?",
          ],
          systemDesign: null,
        },
      ],
    },
    {
      id: "phase-5",
      title: "Phase 5: System Design & Interview Prep",
      color: "#ef4444",
      weeks: "18–20",
      modules: [
        {
          id: "m14",
          title: "Large-Scale System Design",
          week: "Week 18–19",
          icon: "📐",
          duration: "2 weeks",
          description: "Practice designing production systems end-to-end — the final boss of engineering interviews.",
          topics: [
            "System design framework: requirements → scale → API → data model → high-level → deep dive",
            "Back-of-envelope estimation: QPS, storage, bandwidth, latency",
            "Scalability patterns: horizontal scaling, read replicas, caching, CDN, sharding",
            "Availability patterns: redundancy, failover, circuit breakers, graceful degradation",
            "Data consistency models: strong, eventual, causal consistency",
            "Designing for idempotency and exactly-once processing",
            "Rate limiting algorithms: token bucket, leaky bucket, fixed/sliding window",
            "Common system design problems with AI components",
          ],
          labs: [
            {
              title: "Design an AI Feature Store",
              desc: "Design and partially implement a feature store that serves ML features with <10ms latency. Handle both batch and realtime feature computation.",
              difficulty: "advanced",
            },
            {
              title: "Design a Chat Application with AI",
              desc: "Design WhatsApp-scale chat (2B users) with an AI assistant embedded. Cover: messaging, presence, push notifications, AI response generation.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "System Design Primer (GitHub)", url: "https://github.com/donnemartin/system-design-primer" },
            { title: "ByteByteGo Blog", url: "https://blog.bytebytego.com/" },
            { title: "Designing Data-Intensive Applications (Book)", url: "https://dataintensive.net/" },
          ],
          interviewQuestions: [
            "Design YouTube",
            "Design a URL shortener",
            "Design a notification system",
            "Design a rate limiter",
            "Design Twitter's feed",
            "Design a vector search system for 1B vectors",
            "Design an LLM-powered customer support system",
          ],
          systemDesign: {
            prompt: "Design an internal AI platform for a company of 500 engineers. It must support: RAG over internal docs, code generation, and model fine-tuning jobs.",
            hints: [
              "Self-hosted models on GPU cluster (cost control)",
              "Multi-tenant with usage quotas per team",
              "Fine-tuning job queue (Kubernetes Jobs + Argo Workflows)",
              "Model registry (MLflow) and promotion pipeline",
            ],
          },
        },
        {
          id: "m15",
          title: "Interview Preparation",
          week: "Week 20",
          icon: "🎯",
          duration: "1 week",
          description: "Polish your skills, build your portfolio, and ace technical interviews.",
          topics: [
            "Coding interviews: data structures, algorithms (LeetCode Mediums)",
            "API design interviews: REST conventions, versioning, pagination",
            "Architecture walkthroughs: presenting your own projects",
            "Behavioral: STAR method for engineering leadership questions",
            "Live system design practice with a timer",
            "Portfolio projects to showcase (at least 2 end-to-end AI features)",
          ],
          labs: [
            {
              title: "End-to-End Capstone: AI SaaS Platform",
              desc: "Build and deploy a complete AI-powered SaaS: FastAPI + PostgreSQL + Redis + Kafka + Docker + K8s + CI/CD + RAG + monitoring. Present it as your portfolio project.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "LeetCode (Mediums)", url: "https://leetcode.com/problemset/all/?difficulty=MEDIUM" },
            { title: "Pramp (Mock Interviews)", url: "https://www.pramp.com/" },
            { title: "interviewing.io", url: "https://interviewing.io/" },
          ],
          interviewQuestions: [
            "Tell me about a time you had to make a critical architectural decision under pressure.",
            "How would you mentor a junior engineer learning distributed systems?",
            "Describe an AI feature you took from prototype to production.",
            "How do you decide when a prototype is ready for production?",
          ],
          systemDesign: null,
        },
      ],
    },
    {
      id: "phase-6",
      title: "Phase 6: Edge AI & Computer Vision",
      color: "#f97316",
      weeks: "21-26",
      modules: [
        {
          id: "m16",
          title: "Computer Vision Foundations & CNNs from Scratch",
          week: "Week 21-22",
          icon: "👁️",
          duration: "2 weeks",
          description: "Understand how convolutional neural networks actually work — from the mathematics of convolution to backpropagation through conv layers, pooling, batch norm, and modern architectures. No nn.Conv2d black-box usage: you'll implement conv forward/backward passes from scratch.",
          topics: [
            "Image fundamentals: pixels, color spaces (RGB/BGR/HSV/YUV), channel layout (NCHW vs NHWC)",
            "Convolution mathematics: cross-correlation vs convolution, kernel/filter, stride, padding, dilation",
            "Implementing Conv2D from scratch: im2col trick, Toeplitz matrices, direct vs FFT convolution",
            "Backpropagation through conv layers: gradient w.r.t. input, gradient w.r.t. kernel, gradient w.r.t. bias",
            "Pooling layers: max-pool, average-pool, global average pooling, stride-based downsampling",
            "Batch Normalization internals: running mean/var, affine params, train vs eval mode, fusing BN into conv for inference",
            "Activation functions: ReLU, LeakyReLU, GELU, SiLU/Swish — computation cost on edge",
            "Architecture evolution: LeNet → AlexNet → VGG → GoogLeNet → ResNet → MobileNet → EfficientNet",
            "Depthwise separable convolutions: MobileNet's key insight, parameter reduction math",
            "Inverted residuals, squeeze-and-excitation blocks, neural architecture search (EfficientNet/NAS)",
            "Feature Pyramid Networks (FPN), PANet — multi-scale feature extraction",
            "Transfer learning: fine-tuning vs feature extraction, which layers to freeze, domain shift",
            "Loss functions for vision: cross-entropy, focal loss, IoU/GIoU loss, CTC loss for OCR",
            "Data augmentation: geometric transforms, color jitter, Cutout, MixUp, Mosaic (YOLO-style)",
          ],
          labs: [
            {
              title: "Implement Conv2D Forward & Backward from Scratch",
              desc: "Build a Conv2D layer in pure NumPy: forward pass using im2col, backward pass computing dL/dW, dL/db, dL/dX. Verify gradients against PyTorch autograd.",
              difficulty: "advanced",
            },
            {
              title: "Build a CNN Classifier Without nn.Conv2d",
              desc: "Train a 3-layer CNN on CIFAR-10 using your custom Conv2D. Compare accuracy and speed to PyTorch's optimized version.",
              difficulty: "advanced",
            },
            {
              title: "MobileNetV2 from Scratch",
              desc: "Implement inverted residual blocks with depthwise separable convolutions. Count parameters and FLOPs. Compare to ResNet-50 on the same task.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "CS231n: CNNs for Visual Recognition", url: "https://cs231n.stanford.edu/" },
            { title: "MobileNets Paper (Howard et al.)", url: "https://arxiv.org/abs/1704.04861" },
            { title: "EfficientNet Paper (Tan & Le)", url: "https://arxiv.org/abs/1905.11946" },
            { title: "PyTorch Vision Models", url: "https://pytorch.org/vision/stable/models.html" },
          ],
          interviewQuestions: [
            "Explain how backpropagation works through a convolutional layer. What is the gradient of the loss w.r.t. the kernel?",
            "Why are depthwise separable convolutions more efficient than standard convolutions? Derive the parameter and FLOP reduction.",
            "What is the im2col trick and why is it used in practice?",
            "Explain batch normalization. Why does fusing BN into conv weights help inference speed?",
            "How does a residual/skip connection help training? What problem does it solve?",
            "Compare MobileNetV2 inverted residuals to standard ResNet residuals. Why 'inverted'?",
            "What is the receptive field of a CNN? How do dilated convolutions change it?",
            "Why does NHWC layout often run faster than NCHW on edge devices?",
          ],
          systemDesign: {
            prompt: "Design an image classification pipeline for a mobile app that identifies 1000 plant species from camera photos. Target: <100ms inference on a mid-range phone, <5MB model size, >90% top-5 accuracy.",
            hints: [
              "MobileNetV3 or EfficientNet-Lite backbone",
              "Knowledge distillation from a larger teacher model",
              "INT8 quantization with calibration dataset",
              "On-device inference with TFLite or CoreML",
              "Fallback to server for low-confidence predictions",
            ],
          },
        },
        {
          id: "m17",
          title: "Model Quantization & Optimization",
          week: "Week 22-24",
          icon: "🔬",
          duration: "2 weeks",
          description: "The core of Edge AI: making models small and fast enough to run on constrained hardware. Deep dive into quantization theory, calibration, quantization-aware training, pruning, distillation, and their effects on convolution arithmetic.",
          topics: [
            "Why quantization matters: memory bandwidth bottleneck, MAC energy cost (INT8 vs FP32: 30x less energy)",
            "Number representations: FP32, FP16, BF16, INT8, INT4, binary — precision vs range trade-offs",
            "Quantization fundamentals: affine (asymmetric) vs symmetric, per-tensor vs per-channel, scale and zero-point",
            "How quantization changes Conv2D: INT8 matrix multiply, accumulator width (INT32), requantization",
            "Post-Training Quantization (PTQ): static vs dynamic, calibration strategies (min-max, percentile, entropy/KL-divergence)",
            "Quantization-Aware Training (QAT): fake quantization nodes, straight-through estimator (STE), fine-tuning quantized models",
            "Mixed-precision quantization: sensitivity analysis per layer, which layers tolerate INT4 vs need INT8",
            "Weight pruning: unstructured vs structured, magnitude pruning, movement pruning, lottery ticket hypothesis",
            "Knowledge distillation: teacher-student training, soft targets, intermediate feature matching, attention transfer",
            "Operator fusion: Conv+BN+ReLU, depthwise+pointwise fusion, reducing memory reads",
            "ONNX graph optimization: constant folding, dead code elimination, shape inference",
            "Quantization debugging: per-layer error analysis, weight/activation histograms, outlier clamping",
            "INT4 and sub-byte quantization: GPTQ, AWQ, recent advances in ultra-low precision",
            "Hardware-aware quantization: what ARM NEON, Apple ANE, Hexagon DSP actually support",
          ],
          labs: [
            {
              title: "Quantize Conv2D by Hand",
              desc: "Implement affine quantization for a Conv2D layer manually: quantize weights, quantize activations during calibration, perform INT8 matmul with INT32 accumulator, dequantize output. Measure accuracy drop.",
              difficulty: "advanced",
            },
            {
              title: "PTQ vs QAT Comparison",
              desc: "Take a MobileNetV2 trained on CIFAR-10. Apply PTQ (static + dynamic). Then apply QAT for 5 epochs. Compare accuracy, model size, and inference speed on CPU.",
              difficulty: "intermediate",
            },
            {
              title: "Knowledge Distillation Pipeline",
              desc: "Distill ResNet-50 into MobileNetV2 using soft targets + intermediate feature matching. Compare student accuracy vs training from scratch.",
              difficulty: "advanced",
            },
            {
              title: "Mixed-Precision Sensitivity Analysis",
              desc: "Write a script that quantizes one layer at a time to INT8 while keeping others in FP32. Plot per-layer accuracy degradation. Use results to create an optimal mixed-precision policy.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "Quantization White Paper (Gholami et al.)", url: "https://arxiv.org/abs/2103.13630" },
            { title: "PyTorch Quantization Docs", url: "https://pytorch.org/docs/stable/quantization.html" },
            { title: "TensorFlow Model Optimization Toolkit", url: "https://www.tensorflow.org/model_optimization" },
            { title: "ONNX Runtime Quantization", url: "https://onnxruntime.ai/docs/performance/model-optimizations/quantization.html" },
            { title: "Distilling Knowledge in Neural Networks (Hinton)", url: "https://arxiv.org/abs/1503.02531" },
          ],
          interviewQuestions: [
            "Explain the difference between symmetric and asymmetric quantization. When would you choose one over the other?",
            "Walk through how a Conv2D operation works in INT8. What is the role of the INT32 accumulator?",
            "What is the straight-through estimator and why is it needed for QAT?",
            "How does per-channel quantization differ from per-tensor? Why is it better for conv weights?",
            "Explain KL-divergence calibration for PTQ. Why is it better than min-max?",
            "What is structured vs unstructured pruning? Which one actually speeds up inference and why?",
            "How does knowledge distillation work? What are soft targets and why is temperature important?",
            "Your INT8 model has 5% accuracy drop on one class. How do you debug this?",
            "Explain operator fusion. Why does fusing Conv+BN+ReLU reduce inference time?",
            "Compare FP16, BF16, and INT8 for edge inference. When would you use each?",
          ],
          systemDesign: {
            prompt: "Design a quantization pipeline for a company that deploys 50+ vision models to heterogeneous edge devices (ARM CPUs, Qualcomm DSPs, NVIDIA Jetson, Apple Neural Engine). Must handle model versioning, automated accuracy validation, and rollback.",
            hints: [
              "ONNX as the interchange format, device-specific backends (TFLite, CoreML, TensorRT)",
              "Automated PTQ with accuracy gate — fall back to QAT if accuracy drops >1%",
              "Calibration dataset management and versioning",
              "A/B testing framework for model updates on edge fleet",
              "Model registry with metadata (target device, quantization config, accuracy metrics)",
            ],
          },
        },
        {
          id: "m18",
          title: "Edge Deployment & Inference Engines",
          week: "Week 24-25",
          icon: "📱",
          duration: "2 weeks",
          description: "Bridge the gap from trained model to running inference on real edge hardware. Cover inference engines (TFLite, ONNX Runtime, TensorRT, CoreML), model conversion pipelines, on-device optimization, and fleet management.",
          topics: [
            "Edge hardware landscape: ARM Cortex-A/M, Apple Neural Engine, Qualcomm Hexagon DSP, NVIDIA Jetson, Google Coral/Edge TPU, NPUs",
            "TensorFlow Lite: converter, interpreter, delegates (GPU, NNAPI, Hexagon, CoreML, XNNPACK)",
            "ONNX Runtime: execution providers (CPU, CUDA, TensorRT, CoreML, QNN), graph optimization levels",
            "TensorRT: layer fusion, kernel auto-tuning, INT8 calibration, dynamic shapes, engine serialization",
            "CoreML & Apple Neural Engine: coremltools conversion, ML Program format, flexible shapes",
            "OpenCV DNN module: loading ONNX/TFLite/Caffe models, CPU-optimized inference",
            "Model conversion pipeline: PyTorch → ONNX → TFLite/TensorRT/CoreML — common pitfalls",
            "Profiling edge inference: per-layer latency, memory bandwidth, cache misses, thermal throttling",
            "Batching strategies on edge: single-image vs micro-batching, async preprocessing pipeline",
            "On-device training and adaptation: federated learning basics, personalization layers",
            "Model serving at the edge: REST vs gRPC vs local function call, Triton Inference Server on Jetson",
            "OTA model updates: versioning, delta updates, A/B testing, rollback mechanisms",
            "Power and thermal management: dynamic frequency scaling, model switching based on battery/temperature",
            "Edge-cloud hybrid: on-device fast path + cloud fallback, when to offload, latency budgets",
          ],
          labs: [
            {
              title: "PyTorch to TFLite End-to-End",
              desc: "Convert a MobileNetV2 from PyTorch → ONNX → TFLite (FP32 + INT8). Benchmark inference time and accuracy on CPU. Use TFLite's Python interpreter.",
              difficulty: "intermediate",
            },
            {
              title: "TensorRT Optimization on Jetson",
              desc: "Convert a YOLOv8 model to TensorRT with INT8 calibration. Benchmark FPS on Jetson Nano/Orin. Compare to ONNX Runtime and PyTorch.",
              difficulty: "advanced",
            },
            {
              title: "Build a Real-Time Camera Pipeline",
              desc: "OpenCV camera capture → preprocessing → TFLite inference → post-processing → display. Target 30 FPS on laptop CPU with MobileNet classifier.",
              difficulty: "intermediate",
            },
            {
              title: "Model Conversion Test Suite",
              desc: "Build a pytest suite that: converts a model through every path (ONNX, TFLite, CoreML), verifies numerical equivalence (cosine similarity >0.999), benchmarks each format.",
              difficulty: "intermediate",
            },
          ],
          resources: [
            { title: "TensorFlow Lite Guide", url: "https://www.tensorflow.org/lite/guide" },
            { title: "ONNX Runtime Docs", url: "https://onnxruntime.ai/docs/" },
            { title: "TensorRT Developer Guide", url: "https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/" },
            { title: "CoreML Tools", url: "https://coremltools.readme.io/docs" },
            { title: "Google Coral (Edge TPU)", url: "https://coral.ai/docs/" },
          ],
          interviewQuestions: [
            "Walk through the full pipeline from a PyTorch model to running inference on a phone. What are the conversion steps and potential issues?",
            "What is a TFLite delegate? How does NNAPI work on Android?",
            "Explain TensorRT's optimization process. What is kernel auto-tuning?",
            "How would you profile and debug a model that runs at 10 FPS instead of the expected 30 FPS on edge hardware?",
            "What are the trade-offs between running inference on CPU, GPU, DSP, and NPU on a mobile device?",
            "How do you handle dynamic input shapes in TFLite vs TensorRT vs CoreML?",
            "Design an OTA model update system for 100K edge devices. How do you handle versioning, rollback, and A/B testing?",
            "When should you use edge-cloud hybrid inference? Give a concrete example with latency budget analysis.",
          ],
          systemDesign: {
            prompt: "Design a smart security camera system deployed in 500 retail stores. Each store has 8-12 cameras doing real-time person detection + tracking + action recognition. Budget: $200/camera for compute. Requirements: <200ms end-to-end latency, 99.5% uptime, cloud dashboard for alerts.",
            hints: [
              "Edge compute: NVIDIA Jetson Orin Nano or Hailo-8 per camera cluster",
              "Model pipeline: YOLOv8-nano (detection) → ByteTrack (tracking) → lightweight action classifier",
              "INT8 quantization with TensorRT for real-time throughput",
              "Local alert processing + cloud sync for dashboard and model updates",
              "Federated model improvement across stores without sending video to cloud",
            ],
          },
        },
        {
          id: "m19",
          title: "Case Studies: Detection, Classification, OCR & Classical CV",
          week: "Week 25-26",
          icon: "🎯",
          duration: "2 weeks",
          description: "Apply everything to real-world edge AI problems. Deep-dive case studies covering YOLO object detection, image classification, OCR pipelines, and problems best solved with classical computer vision — all optimized for edge deployment.",
          topics: [
            "Object detection fundamentals: anchor-based vs anchor-free, one-stage vs two-stage, NMS, IoU",
            "YOLO family deep dive: YOLOv5 → YOLOv8 → YOLOv11 architecture, loss functions, training strategies",
            "Detection on edge: YOLOv8-nano quantized, SSD-MobileNet, EfficientDet-Lite, NanoDet",
            "Image classification on edge: MobileNet, EfficientNet-Lite, ShuffleNet — accuracy/latency trade-offs",
            "OCR pipeline: text detection (EAST/DBNet) → recognition (CRNN+CTC / TrOCR) → post-processing",
            "Tesseract vs deep-learning OCR: when classical wins, integration with OpenCV preprocessing",
            "Classical CV with OpenCV: thresholding, morphological ops, contour detection, Hough transforms",
            "Barcode/QR code scanning: ZBar, OpenCV, real-time detection pipeline",
            "Document scanning: perspective correction (4-point transform), adaptive thresholding, edge detection",
            "Lane detection: classical (Canny + Hough) vs deep learning (LaneNet), real-time on embedded",
            "Defect detection in manufacturing: anomaly detection, template matching, feature matching (ORB/SIFT)",
            "Face detection and recognition: MTCNN → ArcFace, anti-spoofing, privacy considerations",
            "Pose estimation on edge: MoveNet/BlazePose, applications in fitness/rehab/safety",
            "End-to-end MLOps for edge: data collection → annotation → training → quantization → deployment → monitoring",
          ],
          labs: [
            {
              title: "Real-Time Object Detection Pipeline",
              desc: "Train YOLOv8-nano on a custom dataset (e.g., PPE detection). Export to TFLite INT8. Build a real-time camera pipeline hitting 30+ FPS on CPU.",
              difficulty: "advanced",
            },
            {
              title: "OCR on Edge: License Plate Reader",
              desc: "Build an end-to-end pipeline: camera → plate detection (YOLO) → crop → text recognition (CRNN or Tesseract) → output. Optimize for <200ms total latency.",
              difficulty: "advanced",
            },
            {
              title: "Classical CV: Document Scanner",
              desc: "Build a mobile-style document scanner using only OpenCV: edge detection, contour finding, perspective transform, adaptive threshold for clean B&W output.",
              difficulty: "intermediate",
            },
            {
              title: "Defect Detection with Classical + Deep Learning",
              desc: "Compare template matching (classical) vs anomaly detection (autoencoder) for manufacturing defect detection. Measure accuracy, speed, and edge-readiness.",
              difficulty: "intermediate",
            },
            {
              title: "Edge MLOps Pipeline",
              desc: "Set up a complete pipeline: Label Studio for annotation → PyTorch training → ONNX export → TFLite INT8 → deploy to a simulated edge device → monitor drift.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "Ultralytics YOLOv8 Docs", url: "https://docs.ultralytics.com/" },
            { title: "OpenCV Documentation", url: "https://docs.opencv.org/" },
            { title: "PaddleOCR", url: "https://github.com/PaddlePaddle/PaddleOCR" },
            { title: "Tesseract OCR", url: "https://github.com/tesseract-ocr/tesseract" },
            { title: "Edge Impulse (Edge MLOps)", url: "https://www.edgeimpulse.com/" },
            { title: "Roboflow (Dataset + Deployment)", url: "https://roboflow.com/" },
          ],
          interviewQuestions: [
            "Explain how YOLO works. What makes it faster than two-stage detectors like Faster R-CNN?",
            "What is Non-Maximum Suppression (NMS)? What are its failure modes and alternatives (Soft-NMS, DIoU-NMS)?",
            "Design an OCR pipeline for reading receipts on a mobile phone. What are the key challenges?",
            "When would you use classical CV (OpenCV) instead of deep learning? Give 3 concrete examples.",
            "How would you handle class imbalance in an object detection dataset? What is focal loss?",
            "Explain the CRNN+CTC architecture for text recognition. Why CTC loss instead of cross-entropy?",
            "How do you evaluate an object detection model? Explain mAP, mAP@50, mAP@50:95.",
            "You need to detect defects on a factory line with <50ms latency and 99.9% recall. Design the solution.",
            "What is the difference between anchor-based and anchor-free object detection? Give examples of each.",
            "How would you set up continuous learning for an edge AI system that encounters distribution shift in production?",
          ],
          systemDesign: {
            prompt: "Design an edge AI system for a warehouse that does: (1) real-time package counting on conveyor belts, (2) barcode scanning, (3) damage detection, and (4) worker safety monitoring (PPE compliance). All on a $500 compute budget per station.",
            hints: [
              "Multi-task pipeline: shared backbone (MobileNet) with task-specific heads",
              "Classical CV for barcode scanning (ZBar) — don't waste DNN compute",
              "Anomaly detection autoencoder for damage (unsupervised — no labeled damage data)",
              "YOLOv8-nano for PPE detection, quantized INT8 on Jetson Orin Nano",
              "Pipeline orchestration: prioritize safety alerts, batch counting can be slightly delayed",
              "Edge-cloud sync: counts/alerts → cloud dashboard, images only on anomalies",
            ],
          },
        },
        {
          id: "m20",
          title: "Efficient Architecture Design & Hardware-Aware NAS",
          week: "Week 27-28",
          icon: "🧬",
          duration: "2 weeks",
          description: "Master the art and science of designing neural architectures that are inherently efficient. From manual design principles (depthwise separable convolutions, inverted residuals, compound scaling) to automated Neural Architecture Search — including hardware-aware NAS that optimizes directly for latency and energy on target devices. Covers advanced sparsity (structured, N:M, sparse tensor cores) and combined compression pipelines.",
          topics: [
            "Efficient architecture design principles: parameter efficiency, FLOPs vs actual latency, memory access cost (MAC)",
            "Depthwise separable convolutions deep dive: MobileNetV1/V2/V3, channel-wise design choices",
            "Compound scaling: EfficientNet's width/depth/resolution scaling, scaling laws for edge",
            "ShuffleNet, GhostNet, MCUNet — architectures for extreme resource constraints (microcontrollers)",
            "Neural Architecture Search (NAS): search space design (macro vs micro/cell-based), operation primitives",
            "NAS strategies: reinforcement learning (NASNet), evolutionary (AmoebaNet), differentiable (DARTS), one-shot (OFA)",
            "Hardware-aware NAS: latency lookup tables, FBNet, MnasNet, OFA (Once-for-All), multi-objective Pareto optimization",
            "Differentiable NAS: DARTS, ProxylessNAS, continuous relaxation of discrete search, supernet training",
            "One-shot NAS and weight sharing: supernet training, progressive shrinking, subnet extraction, accuracy predictor",
            "Structured sparsity: channel pruning, filter pruning, block sparsity — actual hardware speedups",
            "NVIDIA 2:4 sparsity: Ampere sparse tensor cores, fine-grained structured sparsity, training with 2:4 constraints",
            "Sparsity-aware training: gradual magnitude pruning, movement pruning, sparse-to-sparse training (RigL)",
            "Combined compression: quantization + pruning + distillation pipelines, compound compression strategies",
            "Cross-platform architecture selection: designing one architecture family deployable across NPU/DSP/GPU/CPU",
          ],
          labs: [
            {
              title: "Design Space Exploration: Build an Efficiency Benchmark",
              desc: "Benchmark MobileNetV3, EfficientNet-Lite, ShuffleNetV2, and GhostNet on CIFAR-100. Measure accuracy, latency (CPU/GPU), model size, and FLOPs. Plot Pareto frontiers.",
              difficulty: "intermediate",
            },
            {
              title: "Implement DARTS from Scratch",
              desc: "Build a simplified DARTS search: define a mixed-op cell, implement bi-level optimization (architecture params + weights), search on CIFAR-10, derive the final architecture.",
              difficulty: "advanced",
            },
            {
              title: "Hardware-Aware NAS with Latency Predictor",
              desc: "Build a latency lookup table for TFLite on CPU. Implement a simple evolutionary NAS that uses predicted latency as a constraint. Find the best architecture under 10ms latency budget.",
              difficulty: "advanced",
            },
            {
              title: "Apply 2:4 Structured Sparsity to a Vision Model",
              desc: "Take a pretrained ResNet-50. Apply NVIDIA ASP (Automatic SParsity) for 2:4 structured sparsity. Fine-tune for 5 epochs. Compare accuracy and simulated speedup to dense baseline.",
              difficulty: "advanced",
            },
            {
              title: "Combined Compression Pipeline",
              desc: "Take EfficientNet-B0: first prune (structured, 50% channels), then distill from unpruned teacher, then quantize to INT8. Measure cumulative compression ratio, accuracy, and latency at each stage.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "MnasNet: Platform-Aware NAS (Tan et al.)", url: "https://arxiv.org/abs/1807.11626" },
            { title: "DARTS: Differentiable Architecture Search (Liu et al.)", url: "https://arxiv.org/abs/1806.09055" },
            { title: "Once-for-All (Cai et al.)", url: "https://arxiv.org/abs/1908.09791" },
            { title: "Accelerating Sparse Deep Neural Networks (NVIDIA)", url: "https://arxiv.org/abs/2104.08378" },
            { title: "EfficientNetV2 (Tan & Le)", url: "https://arxiv.org/abs/2104.00298" },
            { title: "MCUNet (Lin et al.)", url: "https://arxiv.org/abs/2007.10319" },
          ],
          interviewQuestions: [
            "What is the difference between FLOPs and actual inference latency? Why can a model with fewer FLOPs be slower?",
            "Explain how DARTS works. What is the continuous relaxation trick and what are its failure modes?",
            "What is hardware-aware NAS? How does MnasNet incorporate latency into the search objective?",
            "Explain NVIDIA's 2:4 structured sparsity. Why does it guarantee exactly 2x speedup on Ampere GPUs?",
            "Compare one-shot NAS (OFA) to standard NAS. What is weight sharing and why does it make NAS practical?",
            "How do you combine pruning, quantization, and distillation? What order matters and why?",
            "Why might a model optimized for one hardware platform perform poorly on another? Give specific examples.",
            "Explain the difference between unstructured and structured sparsity. Which one gives real speedups and why?",
            "What is compound scaling (EfficientNet)? How do you determine the optimal width/depth/resolution ratio?",
            "Design a NAS pipeline that finds the best model for deployment on both an ARM CPU and an Apple Neural Engine.",
          ],
          systemDesign: {
            prompt: "You are the ML platform lead at a drone company. Design a system that automatically finds and deploys the optimal neural network architecture for each of your 5 drone models (each with different compute hardware: Jetson Orin, Hailo-8, RockChip NPU, Qualcomm QCS, Intel Movidius). The system must search, benchmark, and deploy models that meet latency/accuracy requirements per platform.",
            hints: [
              "Once-for-All supernet trained once, subnets extracted per hardware target",
              "Latency predictor per hardware platform, integrated into search loop",
              "Automated benchmark pipeline: export → quantize → profile on target hardware",
              "Multi-objective search: Pareto-optimal subnets per platform",
              "Model registry tracking architecture configs, hardware benchmarks, accuracy metrics",
              "CI/CD gate: new subnet must meet latency + accuracy thresholds before deployment",
            ],
          },
        },
        {
          id: "m21",
          title: "The Compiler Stack: Model → Compiler → Hardware",
          week: "Week 29-30",
          icon: "🔩",
          duration: "2 weeks",
          description: "Understand the full journey from a trained model to executable code on target hardware. Master ML compilers (TVM, XLA, MLIR, IREE), graph-level and operator-level optimizations, hardware code generation, and kernel auto-tuning. Learn to profile full-stack bottlenecks and resolve them systematically from model IR through compiler passes to hardware execution.",
          topics: [
            "The ML compiler landscape: why compilers matter, the gap between frameworks and hardware",
            "Computation graphs and intermediate representations (IR): relay, TOSA, StableHLO, MLIR dialects",
            "TVM end-to-end: Relay IR → TIR → target codegen, module import/export workflow",
            "XLA (Accelerated Linear Algebra): HLO IR, fusion strategies, XLA:CPU/GPU/TPU backends",
            "MLIR architecture: dialects (linalg, affine, scf, tensor, memref), progressive lowering",
            "IREE compiler and runtime: from StableHLO → Flow → Stream → HAL, cross-platform deployment",
            "Graph-level optimizations: operator fusion, constant folding, layout transformation (NCHW↔NHWC), dead code elimination",
            "Operator-level optimizations: loop tiling, vectorization, unrolling, memory access patterns (cache-friendly layouts)",
            "Kernel auto-tuning: TVM AutoTVM and MetaSchedule, search spaces, cost models, transfer learning across targets",
            "Hardware codegen: LLVM backends, GPU kernel generation (CUDA/OpenCL/Vulkan/Metal), NPU/DSP code paths",
            "Full-stack profiling: model-level → compiler-level → hardware-level bottleneck identification",
            "Custom operator registration: writing custom ops, integrating BYOC (Bring Your Own Codegen) in TVM",
            "Ahead-of-Time (AOT) compilation: static memory planning, microTVM for bare-metal targets",
            "Comparing compiler stacks: TVM vs XLA vs IREE vs TensorRT vs OpenVINO — when to use which",
          ],
          labs: [
            {
              title: "TVM End-to-End Compilation",
              desc: "Take a PyTorch ResNet-18, convert to TVM Relay IR, apply graph optimizations, compile for LLVM (CPU), and benchmark. Compare inference time against PyTorch eager mode.",
              difficulty: "intermediate",
            },
            {
              title: "XLA Compilation with JAX",
              desc: "Implement a vision model in JAX/Flax, inspect the HLO graph, trace XLA's fusion decisions. Compare XLA-compiled vs non-compiled performance on GPU.",
              difficulty: "intermediate",
            },
            {
              title: "MLIR Progressive Lowering",
              desc: "Write a small MLIR program using linalg dialect. Lower it step-by-step through affine → scf → LLVM dialect. Inspect the IR at each stage and understand each transformation.",
              difficulty: "advanced",
            },
            {
              title: "TVM AutoTuning: MetaSchedule",
              desc: "Use TVM MetaSchedule to auto-tune a MobileNetV2 for your CPU. Compare tuned vs untuned performance. Explore search space configurations and cost model accuracy.",
              difficulty: "advanced",
            },
            {
              title: "Full-Stack Bottleneck Resolution",
              desc: "Profile a model end-to-end: identify graph-level issues (operator fusion missed), operator-level issues (suboptimal tiling), and hardware issues (memory bandwidth saturation). Fix each bottleneck and measure improvement.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "TVM Documentation", url: "https://tvm.apache.org/docs/" },
            { title: "XLA: Optimizing Compiler for ML", url: "https://www.tensorflow.org/xla" },
            { title: "MLIR: Multi-Level Intermediate Representation", url: "https://mlir.llvm.org/" },
            { title: "IREE: Intermediate Representation Execution Environment", url: "https://iree.dev/" },
            { title: "TVM: An Automated End-to-End Optimizing Compiler (Chen et al.)", url: "https://arxiv.org/abs/1802.04799" },
            { title: "Ansor: Generating High-Performance Tensor Programs (Zheng et al.)", url: "https://arxiv.org/abs/2006.06762" },
          ],
          interviewQuestions: [
            "Explain the role of an ML compiler. Why can't we just run framework ops directly on hardware?",
            "What is operator fusion and why is it the single most impactful compiler optimization for inference?",
            "Compare TVM Relay IR and MLIR. What are the design trade-offs? Why did the industry move toward MLIR?",
            "Explain how TVM's auto-tuning works. What is the search space and how does MetaSchedule improve over AutoTVM?",
            "What is XLA's HLO IR? How does XLA decide which operations to fuse?",
            "Walk through the full compilation pipeline: PyTorch model → ONNX → TVM Relay → TIR → LLVM IR → machine code.",
            "What is IREE and how does it differ from TVM? When would you choose one over the other?",
            "Explain layout transformation (NCHW vs NHWC). Why does the optimal layout depend on the hardware target?",
            "What is Ahead-of-Time (AOT) compilation in the context of ML? How does it enable deployment on bare-metal MCUs?",
            "You have a model that's 3x slower than expected after compilation. Walk through your full-stack debugging process.",
          ],
          systemDesign: {
            prompt: "You're the compiler infrastructure lead at a chip startup. Your customers ship models to 4 different hardware targets (your NPU, ARM CPU, Qualcomm DSP, Apple ANE). Design a unified compilation platform that: (1) accepts models from PyTorch/TF/ONNX, (2) optimizes and compiles per-target with auto-tuning, (3) validates numerical accuracy across targets, and (4) serves compiled models via a model registry with A/B testing support.",
            hints: [
              "Unified frontend: ONNX → MLIR (or TVM Relay) as canonical IR",
              "Per-target backend pipelines with shared graph-level optimizations",
              "Auto-tuning infrastructure: distributed tuning workers per hardware target",
              "Numerical accuracy validation: golden reference outputs vs compiled outputs, tolerance thresholds",
              "Model registry: versioned compiled artifacts per target, metadata (latency, accuracy, memory)",
              "CI/CD: on model submission, trigger compilation + tuning + validation + benchmark, gate on quality thresholds",
            ],
          },
        },
        {
          id: "m22",
          title: "Scaling Edge ML Pipelines & Multi-Platform CI/CD",
          week: "Week 31-32",
          icon: "🚀",
          duration: "2 weeks",
          description: "Build production-grade infrastructure for training, testing, compiling, and deploying ML models to heterogeneous edge fleets. Master model registries with hardware-specific artifact management, automated benchmark pipelines with regression gates, cross-compilation CI/CD for ARM/NPU/DSP targets, OTA update strategies for edge devices, and fleet-wide monitoring with drift detection. Learn to operate ML at the edge reliably across thousands of devices.",
          topics: [
            "Model registry for edge: versioning compiled artifacts per hardware target, metadata tracking (latency, accuracy, memory, power)",
            "Artifact management: ONNX, TFLite, TVM compiled modules, TensorRT engines — storage, deduplication, lineage",
            "Benchmark infrastructure: automated latency/accuracy/memory profiling on real hardware, CI-integrated benchmark runners",
            "Regression testing: golden-reference outputs, numerical tolerance thresholds, accuracy degradation gates",
            "Cross-compilation pipelines: building for ARM (aarch64, armv7), RISC-V, Qualcomm Hexagon DSP, custom NPUs from x86 CI runners",
            "Multi-platform CI/CD: GitHub Actions matrix builds, self-hosted runners on edge hardware, QEMU-based emulation fallback",
            "Containerized edge builds: Docker multi-arch (buildx), Yocto/OpenEmbedded integration, sysroot management",
            "OTA model updates: delta updates for large models, A/B partition schemes, rollback strategies, bandwidth-constrained deployments",
            "Fleet management: device inventory, capability detection, targeted rollouts (canary → staged → full), device grouping by hardware class",
            "Edge observability: on-device inference telemetry, latency histograms, accuracy monitoring with proxy metrics, anomaly detection",
            "Data and model drift detection at the edge: lightweight drift detectors, triggering retraining pipelines from edge signals",
            "Reproducibility: pinning compiler versions, deterministic builds, bit-exact compilation verification across CI runs",
            "Cost optimization: spot instances for tuning/compilation, caching compiled artifacts, incremental recompilation",
            "Security: model signing and attestation, secure boot chain for ML artifacts, encrypted model storage on device",
          ],
          labs: [
            {
              title: "Model Registry with Hardware Artifacts",
              desc: "Build a model registry (MLflow or custom) that stores compiled artifacts per hardware target. Implement metadata tracking for latency, accuracy, model size, and power consumption. Add API endpoints for querying best model per target.",
              difficulty: "intermediate",
            },
            {
              title: "Multi-Platform CI/CD Pipeline",
              desc: "Create a GitHub Actions pipeline that: (1) exports a PyTorch model to ONNX, (2) cross-compiles for 3 targets (TFLite for ARM CPU, TVM for x86, TensorRT for Jetson), (3) runs benchmark tests on each, (4) gates deployment on latency/accuracy thresholds.",
              difficulty: "advanced",
            },
            {
              title: "Automated Regression Testing",
              desc: "Build a regression test suite that compares model outputs against golden references across compiler versions. Implement numerical tolerance checks, latency regression detection, and automatic bisection to find the offending change.",
              difficulty: "intermediate",
            },
            {
              title: "OTA Model Update System",
              desc: "Implement an OTA update system for edge devices: delta-based model updates, A/B deployment with automatic rollback on accuracy drop, bandwidth estimation, and update scheduling for constrained networks.",
              difficulty: "advanced",
            },
            {
              title: "Fleet Monitoring Dashboard",
              desc: "Build an end-to-end monitoring pipeline: on-device telemetry collection (inference latency, confidence distributions), centralized aggregation, drift detection alerts, and a Grafana dashboard showing fleet-wide model health.",
              difficulty: "advanced",
            },
          ],
          resources: [
            { title: "MLflow Model Registry", url: "https://mlflow.org/docs/latest/model-registry.html" },
            { title: "GitHub Actions: Building and testing", url: "https://docs.github.com/en/actions/automating-builds-and-tests" },
            { title: "Docker Buildx Multi-Platform", url: "https://docs.docker.com/build/building/multi-platform/" },
            { title: "Mender.io OTA Updates", url: "https://mender.io/" },
            { title: "Evidently AI: ML Monitoring", url: "https://www.evidentlyai.com/" },
            { title: "Seldon Core: ML Deployment", url: "https://docs.seldon.io/projects/seldon-core/en/latest/" },
          ],
          interviewQuestions: [
            "How do you version ML models for edge deployment when the same model needs different compiled artifacts per hardware target?",
            "Design a CI/CD pipeline that compiles a model for 5 different hardware targets. How do you handle targets you can't emulate in CI?",
            "What is a golden-reference test for ML models? How do you set numerical tolerance thresholds across different quantization levels?",
            "Explain delta OTA updates for ML models. How do you minimize bandwidth usage when updating a 50MB model on thousands of devices?",
            "How do you detect model drift on edge devices that have limited connectivity? What proxy metrics can you use?",
            "Compare canary deployments for edge ML vs. traditional web services. What makes edge canary rollouts harder?",
            "How do you ensure reproducible compilation? What can cause bit-level differences between two compilation runs of the same model?",
            "Design a fleet management system for 10,000 cameras with 3 different NPU types. How do you roll out model updates safely?",
            "What security measures are needed for ML model deployment on edge devices? Explain model signing and attestation.",
            "How do you handle a regression where a new model is more accurate but 2x slower on one hardware target? What's your decision framework?",
          ],
          systemDesign: {
            prompt: "You are the ML platform lead at an autonomous vehicle company. Design a system that manages the entire lifecycle of ML models across a fleet of 50,000 vehicles with 3 different compute platforms (NVIDIA Orin, Qualcomm SA8650P, Mobileye EyeQ6). The system must handle model training triggers, automated compilation per platform, regression testing, staged rollouts with safety gates, OTA delivery over cellular, on-vehicle monitoring, and automatic rollback if any safety metric degrades.",
            hints: [
              "Model registry with per-platform compiled artifacts, linked to training run metadata and dataset version",
              "CI/CD: on model commit → compile for all 3 platforms → benchmark → golden-reference regression test → safety validation",
              "Staged rollout: shadow mode (run new model alongside production, compare outputs) → canary (1% fleet) → phased (10%, 50%, 100%)",
              "OTA: delta compression, cellular bandwidth scheduling (off-peak), resume-on-disconnect, cryptographic signing",
              "On-vehicle monitoring: inference latency, confidence calibration, safety-critical metric tracking, edge-side anomaly detection",
              "Automatic rollback trigger: if P99 latency exceeds threshold OR safety metric degrades beyond tolerance on canary group",
            ],
          },
        },
      ],
    },
  ],
};

if (typeof module !== "undefined") module.exports = CURRICULUM;
